(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form u Log[e (f (a+b x)^p (c+d x)^q)^r]^s*)


(* ::Section::Closed:: *)
(*Integrands of the form (g+h x)^m Log[e (f (a+b x)^p (c+d x)^q)^r]^s*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m Log[e (f (a+b x)^p (c+d x)^q)^r]^s*)


{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*(a + b*x)^4, x, 4, -(((b*c - a*d)^4*q*r*x)/(5*d^4)) + ((b*c - a*d)^3*q*r*(a + b*x)^2)/(10*b*d^3) - ((b*c - a*d)^2*q*r*(a + b*x)^3)/(15*b*d^2) + ((b*c - a*d)*q*r*(a + b*x)^4)/(20*b*d) - (p*r*(a + b*x)^5)/(25*b) - (q*r*(a + b*x)^5)/(25*b) + ((b*c - a*d)^5*q*r*Log[c + d*x])/(5*b*d^5) + ((a + b*x)^5*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(5*b)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*(a + b*x)^3, x, 4, ((b*c - a*d)^3*q*r*x)/(4*d^3) - ((b*c - a*d)^2*q*r*(a + b*x)^2)/(8*b*d^2) + ((b*c - a*d)*q*r*(a + b*x)^3)/(12*b*d) - (p*r*(a + b*x)^4)/(16*b) - (q*r*(a + b*x)^4)/(16*b) - ((b*c - a*d)^4*q*r*Log[c + d*x])/(4*b*d^4) + ((a + b*x)^4*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(4*b)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*(a + b*x)^2, x, 4, -(((b*c - a*d)^2*q*r*x)/(3*d^2)) + ((b*c - a*d)*q*r*(a + b*x)^2)/(6*b*d) - (p*r*(a + b*x)^3)/(9*b) - (q*r*(a + b*x)^3)/(9*b) + ((b*c - a*d)^3*q*r*Log[c + d*x])/(3*b*d^3) + ((a + b*x)^3*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(3*b)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*(a + b*x)^1, x, 4, (-(1/2))*a*p*r*x + ((b*c - a*d)*q*r*x)/(2*d) - (1/4)*b*p*r*x^2 - (q*r*(a + b*x)^2)/(4*b) - ((b*c - a*d)^2*q*r*Log[c + d*x])/(2*b*d^2) + ((a + b*x)^2*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(2*b)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(a + b*x)^1, x, 6, -((p*r*Log[a + b*x]^2)/(2*b)) - (q*r*Log[a + b*x]*Log[(b*(c + d*x))/(b*c - a*d)])/b + (Log[a + b*x]*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/b - (q*r*PolyLog[2, -((d*(a + b*x))/(b*c - a*d))])/b}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(a + b*x)^2, x, 5, -((p*r)/(b*(a + b*x))) + (d*q*r*Log[a + b*x])/(b*(b*c - a*d)) - (d*q*r*Log[c + d*x])/(b*(b*c - a*d)) - Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(b*(a + b*x))}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(a + b*x)^3, x, 4, -((p*r)/(4*b*(a + b*x)^2)) - (d*q*r)/(2*b*(b*c - a*d)*(a + b*x)) - (d^2*q*r*Log[a + b*x])/(2*b*(b*c - a*d)^2) + (d^2*q*r*Log[c + d*x])/(2*b*(b*c - a*d)^2) - Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(2*b*(a + b*x)^2)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(a + b*x)^4, x, 4, -((p*r)/(9*b*(a + b*x)^3)) - (d*q*r)/(6*b*(b*c - a*d)*(a + b*x)^2) + (d^2*q*r)/(3*b*(b*c - a*d)^2*(a + b*x)) + (d^3*q*r*Log[a + b*x])/(3*b*(b*c - a*d)^3) - (d^3*q*r*Log[c + d*x])/(3*b*(b*c - a*d)^3) - Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(3*b*(a + b*x)^3)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(a + b*x)^5, x, 4, -((p*r)/(16*b*(a + b*x)^4)) - (d*q*r)/(12*b*(b*c - a*d)*(a + b*x)^3) + (d^2*q*r)/(8*b*(b*c - a*d)^2*(a + b*x)^2) - (d^3*q*r)/(4*b*(b*c - a*d)^3*(a + b*x)) - (d^4*q*r*Log[a + b*x])/(4*b*(b*c - a*d)^4) + (d^4*q*r*Log[c + d*x])/(4*b*(b*c - a*d)^4) - Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(4*b*(a + b*x)^4)}


(* ::Subsection::Closed:: *)
(*Integrands of the form (g+h x)^m Log[e (f (a+b x)^p (c+d x)^q)^r]^s*)


{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*(g + h*x)^4, x, 5, -(((b*g - a*h)^4*p*r*x)/(5*b^4)) - ((d*g - c*h)^4*q*r*x)/(5*d^4) - ((b*g - a*h)^3*p*r*(g + h*x)^2)/(10*b^3*h) - ((d*g - c*h)^3*q*r*(g + h*x)^2)/(10*d^3*h) - ((b*g - a*h)^2*p*r*(g + h*x)^3)/(15*b^2*h) - ((d*g - c*h)^2*q*r*(g + h*x)^3)/(15*d^2*h) - ((b*g - a*h)*p*r*(g + h*x)^4)/(20*b*h) - ((d*g - c*h)*q*r*(g + h*x)^4)/(20*d*h) - (p*r*(g + h*x)^5)/(25*h) - (q*r*(g + h*x)^5)/(25*h) - ((b*g - a*h)^5*p*r*Log[a + b*x])/(5*b^5*h) - ((d*g - c*h)^5*q*r*Log[c + d*x])/(5*d^5*h) + ((g + h*x)^5*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(5*h)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*(g + h*x)^3, x, 5, -(((b*g - a*h)^3*p*r*x)/(4*b^3)) - ((d*g - c*h)^3*q*r*x)/(4*d^3) - ((b*g - a*h)^2*p*r*(g + h*x)^2)/(8*b^2*h) - ((d*g - c*h)^2*q*r*(g + h*x)^2)/(8*d^2*h) - ((b*g - a*h)*p*r*(g + h*x)^3)/(12*b*h) - ((d*g - c*h)*q*r*(g + h*x)^3)/(12*d*h) - (p*r*(g + h*x)^4)/(16*h) - (q*r*(g + h*x)^4)/(16*h) - ((b*g - a*h)^4*p*r*Log[a + b*x])/(4*b^4*h) - ((d*g - c*h)^4*q*r*Log[c + d*x])/(4*d^4*h) + ((g + h*x)^4*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(4*h)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*(g + h*x)^2, x, 5, -(((b*g - a*h)^2*p*r*x)/(3*b^2)) - ((d*g - c*h)^2*q*r*x)/(3*d^2) - ((b*g - a*h)*p*r*(g + h*x)^2)/(6*b*h) - ((d*g - c*h)*q*r*(g + h*x)^2)/(6*d*h) - (p*r*(g + h*x)^3)/(9*h) - (q*r*(g + h*x)^3)/(9*h) - ((b*g - a*h)^3*p*r*Log[a + b*x])/(3*b^3*h) - ((d*g - c*h)^3*q*r*Log[c + d*x])/(3*d^3*h) + ((g + h*x)^3*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(3*h)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*(g + h*x)^1, x, 5, -(((b*g - a*h)*p*r*x)/(2*b)) - ((d*g - c*h)*q*r*x)/(2*d) - (p*r*(g + h*x)^2)/(4*h) - (q*r*(g + h*x)^2)/(4*h) - ((b*g - a*h)^2*p*r*Log[a + b*x])/(2*b^2*h) - ((d*g - c*h)^2*q*r*Log[c + d*x])/(2*d^2*h) + ((g + h*x)^2*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(2*h)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*(g + h*x)^0, x, 3, -((p + q)*r*x) + ((b*c - a*d)*q*r*Log[c + d*x])/(b*d) + ((a + b*x)*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/b}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(g + h*x)^1, x, 7, -((p*r*Log[-((h*(a + b*x))/(b*g - a*h))]*Log[g + h*x])/h) - (q*r*Log[-((h*(c + d*x))/(d*g - c*h))]*Log[g + h*x])/h + (Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]*Log[g + h*x])/h - (p*r*PolyLog[2, (b*(g + h*x))/(b*g - a*h)])/h - (q*r*PolyLog[2, (d*(g + h*x))/(d*g - c*h)])/h}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(g + h*x)^2, x, 7, (b*p*r*Log[a + b*x])/(h*(b*g - a*h)) + (d*q*r*Log[c + d*x])/(h*(d*g - c*h)) - Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(h*(g + h*x)) - (b*p*r*Log[g + h*x])/(h*(b*g - a*h)) - (d*q*r*Log[g + h*x])/(h*(d*g - c*h))}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(g + h*x)^3, x, 5, (b*p*r)/(2*h*(b*g - a*h)*(g + h*x)) + (d*q*r)/(2*h*(d*g - c*h)*(g + h*x)) + (b^2*p*r*Log[a + b*x])/(2*h*(b*g - a*h)^2) + (d^2*q*r*Log[c + d*x])/(2*h*(d*g - c*h)^2) - Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(2*h*(g + h*x)^2) - (b^2*p*r*Log[g + h*x])/(2*h*(b*g - a*h)^2) - (d^2*q*r*Log[g + h*x])/(2*h*(d*g - c*h)^2)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(g + h*x)^4, x, 5, (b*p*r)/(6*h*(b*g - a*h)*(g + h*x)^2) + (d*q*r)/(6*h*(d*g - c*h)*(g + h*x)^2) + (b^2*p*r)/(3*h*(b*g - a*h)^2*(g + h*x)) + (d^2*q*r)/(3*h*(d*g - c*h)^2*(g + h*x)) + (b^3*p*r*Log[a + b*x])/(3*h*(b*g - a*h)^3) + (d^3*q*r*Log[c + d*x])/(3*h*(d*g - c*h)^3) - Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(3*h*(g + h*x)^3) - (b^3*p*r*Log[g + h*x])/(3*h*(b*g - a*h)^3) - (d^3*q*r*Log[g + h*x])/(3*h*(d*g - c*h)^3)}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(g + h*x)^5, x, 5, (b*p*r)/(12*h*(b*g - a*h)*(g + h*x)^3) + (d*q*r)/(12*h*(d*g - c*h)*(g + h*x)^3) + (b^2*p*r)/(8*h*(b*g - a*h)^2*(g + h*x)^2) + (d^2*q*r)/(8*h*(d*g - c*h)^2*(g + h*x)^2) + (b^3*p*r)/(4*h*(b*g - a*h)^3*(g + h*x)) + (d^3*q*r)/(4*h*(d*g - c*h)^3*(g + h*x)) + (b^4*p*r*Log[a + b*x])/(4*h*(b*g - a*h)^4) + (d^4*q*r*Log[c + d*x])/(4*h*(d*g - c*h)^4) - Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(4*h*(g + h*x)^4) - (b^4*p*r*Log[g + h*x])/(4*h*(b*g - a*h)^4) - (d^4*q*r*Log[g + h*x])/(4*h*(d*g - c*h)^4)}


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m Log[e ((a+b x) / (c+d x))^n]^p*)


{Log[e*((a + b*x)/(c + d*x))^n]^4, x, 6, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^4)/b + (4*(b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n]^3*Log[(b*c - a*d)/(b*(c + d*x))])/(b*d) + (12*(b*c - a*d)*n^2*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (24*(b*c - a*d)*n^3*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) + (24*(b*c - a*d)*n^4*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d)}
{Log[e*((a + b*x)/(c + d*x))^n]^3, x, 5, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^3)/b + (3*(b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))])/(b*d) + (6*(b*c - a*d)*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (6*(b*c - a*d)*n^3*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d)}
{Log[e*((a + b*x)/(c + d*x))^n]^2, x, 7, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^2)/b + (2*(b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(b*d) + (2*(b*c - a*d)*n^2*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b*d)}
{Log[e*((a + b*x)/(c + d*x))^n]^1, x, 3, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/b - ((b*c - a*d)*n*Log[c + d*x])/(b*d)}
{Log[e*((a + b*x)/(c + d*x))^n]^(-1), x, 0, CannotIntegrate[1/Log[e*((a + b*x)/(c + d*x))^n], x]}
{Log[e*((a + b*x)/(c + d*x))^n]^(-2), x, 0, CannotIntegrate[1/Log[e*((a + b*x)/(c + d*x))^n]^2, x]}


{Log[e*((a + b*x)/(c + d*x))^n]^3/x, x, 9, (-Log[e*((a + b*x)/(c + d*x))^n]^3)*Log[(b*c - a*d)/(b*(c + d*x))] + Log[e*((a + b*x)/(c + d*x))^n]^3*Log[-(((b*c - a*d)*x)/(a*(c + d*x)))] - 3*n*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))] + 3*n*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[2, 1 + ((b*c - a*d)*x)/(a*(c + d*x))] + 6*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))] - 6*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[3, 1 + ((b*c - a*d)*x)/(a*(c + d*x))] - 6*n^3*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))] + 6*n^3*PolyLog[4, 1 + ((b*c - a*d)*x)/(a*(c + d*x))]}
{Log[e*((a + b*x)/(c + d*x))^n]^2/x, x, 7, (-Log[e*((a + b*x)/(c + d*x))^n]^2)*Log[(b*c - a*d)/(b*(c + d*x))] + Log[e*((a + b*x)/(c + d*x))^n]^2*Log[-(((b*c - a*d)*x)/(a*(c + d*x)))] - 2*n*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))] + 2*n*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 + ((b*c - a*d)*x)/(a*(c + d*x))] + 2*n^2*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))] - 2*n^2*PolyLog[3, 1 + ((b*c - a*d)*x)/(a*(c + d*x))]}
{Log[e*((a + b*x)/(c + d*x))^n]^1/x, x, 5, (-n)*Log[x]*Log[1 + (b*x)/a] + Log[x]*Log[e*((a + b*x)/(c + d*x))^n] + n*Log[x]*Log[1 + (d*x)/c] - n*PolyLog[2, -((b*x)/a)] + n*PolyLog[2, -((d*x)/c)]}
{1/(x*Log[e*((a + b*x)/(c + d*x))^n]^1), x, 0, Unintegrable[1/(x*Log[e*((a + b*x)/(c + d*x))^n]), x]}
{1/(x*Log[e*((a + b*x)/(c + d*x))^n]^2), x, 0, Unintegrable[1/(x*Log[e*((a + b*x)/(c + d*x))^n]^2), x]}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m Log[e ((a+b x) / (c+d x))^n]^p*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{Log[e*(a + b*x)/(c + d*x)]*(a + b*x)^3, x, 3, -(((b*c - a*d)^3*x)/(4*d^3)) + ((b*c - a*d)^2*(a + b*x)^2)/(8*b*d^2) - ((b*c - a*d)*(a + b*x)^3)/(12*b*d) + ((a + b*x)^4*Log[(e*(a + b*x))/(c + d*x)])/(4*b) + ((b*c - a*d)^4*Log[c + d*x])/(4*b*d^4)}
{Log[e*(a + b*x)/(c + d*x)]*(a + b*x)^2, x, 3, ((b*c - a*d)^2*x)/(3*d^2) - ((b*c - a*d)*(a + b*x)^2)/(6*b*d) + ((a + b*x)^3*Log[(e*(a + b*x))/(c + d*x)])/(3*b) - ((b*c - a*d)^3*Log[c + d*x])/(3*b*d^3)}
{Log[e*(a + b*x)/(c + d*x)]*(a + b*x)^1, x, 3, -(((b*c - a*d)*x)/(2*d)) + ((a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(2*b) + ((b*c - a*d)^2*Log[c + d*x])/(2*b*d^2)}
{Log[e*(a + b*x)/(c + d*x)]*(a + b*x)^0, x, 3, ((a + b*x)*Log[e*(a + b*x)/(c + d*x)])/b - ((b*c - a*d)*Log[c + d*x])/(b*d)}
{Log[e*(a + b*x)/(c + d*x)]/(a + b*x)^1, x, 5, -((Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)])/b) + PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))]/b}
{Log[e*(a + b*x)/(c + d*x)]/(a + b*x)^2, x, 2, -(1/(b*(a + b*x))) - ((c + d*x)*Log[(e*(a + b*x))/(c + d*x)])/((b*c - a*d)*(a + b*x))}
{Log[e*(a + b*x)/(c + d*x)]/(a + b*x)^3, x, 3, -(1/(4*b*(a + b*x)^2)) + d/(2*b*(b*c - a*d)*(a + b*x)) + (d^2*Log[a + b*x])/(2*b*(b*c - a*d)^2) - Log[(e*(a + b*x))/(c + d*x)]/(2*b*(a + b*x)^2) - (d^2*Log[c + d*x])/(2*b*(b*c - a*d)^2)}


{Log[e*(a + b*x)/(c + d*x)]^2*(a + b*x)^3, x, 17, -((5*(b*c - a*d)^3*x)/(12*d^3)) + ((b*c - a*d)^2*(a + b*x)^2)/(12*b*d^2) - ((b*c - a*d)^3*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/(2*b*d^3) + ((b*c - a*d)^2*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(4*b*d^2) - ((b*c - a*d)*(a + b*x)^3*Log[(e*(a + b*x))/(c + d*x)])/(6*b*d) - ((b*c - a*d)^4*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(2*b*d^4) + ((a + b*x)^4*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*b) + (11*(b*c - a*d)^4*Log[c + d*x])/(12*b*d^4) - ((b*c - a*d)^4*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(2*b*d^4)}
{Log[e*(a + b*x)/(c + d*x)]^2*(a + b*x)^2, x, 14, ((b*c - a*d)^2*x)/(3*d^2) + (2*(b*c - a*d)^2*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/(3*b*d^2) - ((b*c - a*d)*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(3*b*d) + (2*(b*c - a*d)^3*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(3*b*d^3) + ((a + b*x)^3*Log[(e*(a + b*x))/(c + d*x)]^2)/(3*b) - ((b*c - a*d)^3*Log[c + d*x])/(b*d^3) + (2*(b*c - a*d)^3*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(3*b*d^3)}
{Log[e*(a + b*x)/(c + d*x)]^2*(a + b*x)^1, x, 11, -(((b*c - a*d)*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/(b*d)) - ((b*c - a*d)^2*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(b*d^2) + ((a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*b) + ((b*c - a*d)^2*Log[c + d*x])/(b*d^2) - ((b*c - a*d)^2*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b*d^2)}
{Log[e*(a + b*x)/(c + d*x)]^2*(a + b*x)^0, x, 7, (2*(b*c - a*d)*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(b*d) + ((a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/b + (2*(b*c - a*d)*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b*d)}
{Log[e*(a + b*x)/(c + d*x)]^2/(a + b*x)^1, x, 3, -((Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)]^2)/b) + (2*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/b + (2*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/b}
{Log[e*(a + b*x)/(c + d*x)]^2/(a + b*x)^2, x, 3, -(2/(b*(a + b*x))) - (2*(c + d*x)*Log[(e*(a + b*x))/(c + d*x)])/((b*c - a*d)*(a + b*x)) - ((c + d*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/((b*c - a*d)*(a + b*x))}
{Log[e*(a + b*x)/(c + d*x)]^2/(a + b*x)^3, x, 7, (2*d)/(b*(b*c - a*d)*(a + b*x)) - (b*(c + d*x)^2)/(4*(b*c - a*d)^2*(a + b*x)^2) + (2*d*(c + d*x)*Log[(e*(a + b*x))/(c + d*x)])/((b*c - a*d)^2*(a + b*x)) - (b*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(2*(b*c - a*d)^2*(a + b*x)^2) + (d*(c + d*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/((b*c - a*d)^2*(a + b*x)) - (b*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*(b*c - a*d)^2*(a + b*x)^2)}


(* {Log[e*(a + b*x)/(c + d*x)]^3*(a + b*x)^3, x, 26, -(((b*c - a*d)^3*x)/(4*d^3)) - (5*(b*c - a*d)^3*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/(4*b*d^3) + ((b*c - a*d)^2*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(4*b*d^2) - (11*(b*c - a*d)^4*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(4*b*d^4) - (3*(b*c - a*d)^3*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*b*d^3) + (3*(b*c - a*d)^2*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(8*b*d^2) - ((b*c - a*d)*(a + b*x)^3*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*b*d) - (3*(b*c - a*d)^4*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*b*d^4) + ((a + b*x)^4*Log[(e*(a + b*x))/(c + d*x)]^3)/(4*b) + (3*(b*c - a*d)^4*Log[c + d*x])/(2*b*d^4) - (11*(b*c - a*d)^4*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(4*b*d^4) - (3*(b*c - a*d)^4*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(2*b*d^4) + (3*(b*c - a*d)^4*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(2*b*d^4)} *)
{Log[e*(a + b*x)/(c + d*x)]^3*(a + b*x)^2, x, 24, ((b*c - a*d)^2*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/(b*d^2) + (3*(b*c - a*d)^3*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(b*d^3) + ((b*c - a*d)^2*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/(b*d^2) - ((b*c - a*d)*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*b*d) + ((b*c - a*d)^3*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)]^2)/(b*d^3) + ((a + b*x)^3*Log[(e*(a + b*x))/(c + d*x)]^3)/(3*b) - ((b*c - a*d)^3*Log[c + d*x])/(b*d^3) + (3*(b*c - a*d)^3*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b*d^3) + (2*(b*c - a*d)^3*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d^3) - (2*(b*c - a*d)^3*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d^3)}
{Log[e*(a + b*x)/(c + d*x)]^3*(a + b*x)^1, x, 13, -((3*(b*c - a*d)^2*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(b*d^2)) - (3*(b*c - a*d)*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*b*d) - (3*(b*c - a*d)^2*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*b*d^2) + ((a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)]^3)/(2*b) - (3*(b*c - a*d)^2*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b*d^2) - (3*(b*c - a*d)^2*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d^2) + (3*(b*c - a*d)^2*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d^2)}
{Log[e*(a + b*x)/(c + d*x)]^3*(a + b*x)^0, x, 5, (3*(b*c - a*d)*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)]^2)/(b*d) + ((a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^3)/b + (6*(b*c - a*d)*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (6*(b*c - a*d)*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d)}
{Log[e*(a + b*x)/(c + d*x)]^3/(a + b*x)^1, x, 4, -((Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)]^3)/b) + (3*Log[(e*(a + b*x))/(c + d*x)]^2*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/b + (6*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/b + (6*PolyLog[4, 1 + (b*c - a*d)/(d*(a + b*x))])/b}
{Log[e*(a + b*x)/(c + d*x)]^3/(a + b*x)^2, x, 4, -(6/(b*(a + b*x))) - (6*(c + d*x)*Log[(e*(a + b*x))/(c + d*x)])/((b*c - a*d)*(a + b*x)) - (3*(c + d*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/((b*c - a*d)*(a + b*x)) - ((c + d*x)*Log[(e*(a + b*x))/(c + d*x)]^3)/((b*c - a*d)*(a + b*x))}
{Log[e*(a + b*x)/(c + d*x)]^3/(a + b*x)^3, x, 9, (6*d)/(b*(b*c - a*d)*(a + b*x)) - (3*b*(c + d*x)^2)/(8*(b*c - a*d)^2*(a + b*x)^2) + (6*d*(c + d*x)*Log[(e*(a + b*x))/(c + d*x)])/((b*c - a*d)^2*(a + b*x)) - (3*b*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(4*(b*c - a*d)^2*(a + b*x)^2) + (3*d*(c + d*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/((b*c - a*d)^2*(a + b*x)) - (3*b*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*(b*c - a*d)^2*(a + b*x)^2) + (d*(c + d*x)*Log[(e*(a + b*x))/(c + d*x)]^3)/((b*c - a*d)^2*(a + b*x)) - (b*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)]^3)/(2*(b*c - a*d)^2*(a + b*x)^2)}


(* ::Subsubsection:: *)
(*p<0*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (c+d x)^m Log[e ((a+b x) / (c+d x))^n]^p*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{Log[e*((a + b*x)/(c + d*x))^n]*(c + d*x)^3, x, 3, -(((b*c - a*d)^3*n*x)/(4*b^3)) - ((b*c - a*d)^2*n*(c + d*x)^2)/(8*b^2*d) - ((b*c - a*d)*n*(c + d*x)^3)/(12*b*d) - ((b*c - a*d)^4*n*Log[a + b*x])/(4*b^4*d) + ((c + d*x)^4*Log[e*((a + b*x)/(c + d*x))^n])/(4*d)}
{Log[e*((a + b*x)/(c + d*x))^n]*(c + d*x)^2, x, 3, -(((b*c - a*d)^2*n*x)/(3*b^2)) - ((b*c - a*d)*n*(c + d*x)^2)/(6*b*d) - ((b*c - a*d)^3*n*Log[a + b*x])/(3*b^3*d) + ((c + d*x)^3*Log[e*((a + b*x)/(c + d*x))^n])/(3*d)}
{Log[e*((a + b*x)/(c + d*x))^n]*(c + d*x)^1, x, 3, -(((b*c - a*d)*n*x)/(2*b)) - ((b*c - a*d)^2*n*Log[a + b*x])/(2*b^2*d) + ((c + d*x)^2*Log[e*((a + b*x)/(c + d*x))^n])/(2*d)}
{Log[e*((a + b*x)/(c + d*x))^n]*(c + d*x)^0, x, 3, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/b - ((b*c - a*d)*n*Log[c + d*x])/(b*d)}
{Log[e*((a + b*x)/(c + d*x))^n]/(c + d*x)^1, x, 5, -((Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/d) - (n*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/d}
{Log[e*((a + b*x)/(c + d*x))^n]/(c + d*x)^2, x, 2, n/(d*(c + d*x)) + ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/((b*c - a*d)*(c + d*x))}
{Log[e*((a + b*x)/(c + d*x))^n]/(c + d*x)^3, x, 3, n/(4*d*(c + d*x)^2) + (b*n)/(2*d*(b*c - a*d)*(c + d*x)) + (b^2*n*Log[a + b*x])/(2*d*(b*c - a*d)^2) - Log[e*((a + b*x)/(c + d*x))^n]/(2*d*(c + d*x)^2) - (b^2*n*Log[c + d*x])/(2*d*(b*c - a*d)^2)}
{Log[e*((a + b*x)/(c + d*x))^n]/(c + d*x)^4, x, 3, n/(9*d*(c + d*x)^3) + (b*n)/(6*d*(b*c - a*d)*(c + d*x)^2) + (b^2*n)/(3*d*(b*c - a*d)^2*(c + d*x)) + (b^3*n*Log[a + b*x])/(3*d*(b*c - a*d)^3) - Log[e*((a + b*x)/(c + d*x))^n]/(3*d*(c + d*x)^3) - (b^3*n*Log[c + d*x])/(3*d*(b*c - a*d)^3)}


{Log[e*(a + b*x)/(c + d*x)]^2*(c + d*x)^3, x, 17, (5*(b*c - a*d)^3*x)/(12*b^3) + ((b*c - a*d)^2*(c + d*x)^2)/(12*b^2*d) + (5*(b*c - a*d)^4*Log[a + b*x])/(12*b^4*d) - ((b*c - a*d)^3*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/(2*b^4) - ((b*c - a*d)^2*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(4*b^2*d) - ((b*c - a*d)*(c + d*x)^3*Log[(e*(a + b*x))/(c + d*x)])/(6*b*d) + ((b*c - a*d)^4*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)])/(2*b^4*d) + ((c + d*x)^4*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*d) + ((b*c - a*d)^4*Log[c + d*x])/(2*b^4*d) - ((b*c - a*d)^4*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(2*b^4*d)}
{Log[e*(a + b*x)/(c + d*x)]^2*(c + d*x)^2, x, 14, ((b*c - a*d)^2*x)/(3*b^2) + ((b*c - a*d)^3*Log[a + b*x])/(3*b^3*d) - (2*(b*c - a*d)^2*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/(3*b^3) - ((b*c - a*d)*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(3*b*d) + (2*(b*c - a*d)^3*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)])/(3*b^3*d) + ((c + d*x)^3*Log[(e*(a + b*x))/(c + d*x)]^2)/(3*d) + (2*(b*c - a*d)^3*Log[c + d*x])/(3*b^3*d) - (2*(b*c - a*d)^3*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(3*b^3*d)}
{Log[e*(a + b*x)/(c + d*x)]^2*(c + d*x)^1, x, 11, -(((b*c - a*d)*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/b^2) + ((b*c - a*d)^2*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)])/(b^2*d) + ((c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*d) + ((b*c - a*d)^2*Log[c + d*x])/(b^2*d) - ((b*c - a*d)^2*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^2*d)}
{Log[e*(a + b*x)/(c + d*x)]^2*(c + d*x)^0, x, 7, (2*(b*c - a*d)*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(b*d) + ((a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/b + (2*(b*c - a*d)*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b*d)}
{Log[e*(a + b*x)/(c + d*x)]^2/(c + d*x)^1, x, 3, -((Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)]^2)/d) - (2*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/d + (2*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/d}
{Log[e*(a + b*x)/(c + d*x)]^2/(c + d*x)^2, x, 3, -(2/(d*(c + d*x))) - (2*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/((b*c - a*d)*(c + d*x)) + ((a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/((b*c - a*d)*(c + d*x))}
{Log[e*(a + b*x)/(c + d*x)]^2/(c + d*x)^3, x, 7, -((d*(a + b*x)^2)/(4*(b*c - a*d)^2*(c + d*x)^2)) - (2*b)/(d*(b*c - a*d)*(c + d*x)) + (d*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(2*(b*c - a*d)^2*(c + d*x)^2) - (2*b*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/((b*c - a*d)^2*(c + d*x)) - (d*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*(b*c - a*d)^2*(c + d*x)^2) + (b*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/((b*c - a*d)^2*(c + d*x))}


(* {Log[e*(a + b*x)/(c + d*x)]^3*(c + d*x)^3, x, 26, -(((b*c - a*d)^3*x)/(4*b^3)) - ((b*c - a*d)^4*Log[a + b*x])/(4*b^4*d) + (5*(b*c - a*d)^3*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/(4*b^4) + ((b*c - a*d)^2*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(4*b^2*d) - (5*(b*c - a*d)^4*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)])/(4*b^4*d) - (3*(b*c - a*d)^4*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(2*b^4*d) - (3*(b*c - a*d)^3*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*b^4) - (3*(b*c - a*d)^2*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(8*b^2*d) - ((b*c - a*d)*(c + d*x)^3*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*b*d) + (3*(b*c - a*d)^4*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*b^4*d) + ((c + d*x)^4*Log[(e*(a + b*x))/(c + d*x)]^3)/(4*d) - (5*(b*c - a*d)^4*Log[c + d*x])/(4*b^4*d) - (3*(b*c - a*d)^4*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(2*b^4*d) + (5*(b*c - a*d)^4*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(4*b^4*d) - (3*(b*c - a*d)^4*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(2*b^4*d) - (3*(b*c - a*d)^4*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/(2*b^4*d)} *)
{Log[e*(a + b*x)/(c + d*x)]^3*(c + d*x)^2, x, 24, ((b*c - a*d)^2*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/b^3 - ((b*c - a*d)^3*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)])/(b^3*d) - (2*(b*c - a*d)^3*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(b^3*d) - ((b*c - a*d)^2*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/b^3 - ((b*c - a*d)*(c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*b*d) + ((b*c - a*d)^3*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)]^2)/(b^3*d) + ((c + d*x)^3*Log[(e*(a + b*x))/(c + d*x)]^3)/(3*d) - ((b*c - a*d)^3*Log[c + d*x])/(b^3*d) - (2*(b*c - a*d)^3*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b^3*d) + ((b*c - a*d)^3*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^3*d) - (2*(b*c - a*d)^3*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^3*d) - (2*(b*c - a*d)^3*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^3*d)}
{Log[e*(a + b*x)/(c + d*x)]^3*(c + d*x)^1, x, 13, -((3*(b*c - a*d)^2*Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)])/(b^2*d)) - (3*(b*c - a*d)*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*b^2) + (3*(b*c - a*d)^2*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[(e*(a + b*x))/(c + d*x)]^2)/(2*b^2*d) + ((c + d*x)^2*Log[(e*(a + b*x))/(c + d*x)]^3)/(2*d) - (3*(b*c - a*d)^2*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b^2*d) - (3*(b*c - a*d)^2*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^2*d) - (3*(b*c - a*d)^2*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^2*d)}
{Log[e*(a + b*x)/(c + d*x)]^3*(c + d*x)^0, x, 5, (3*(b*c - a*d)*Log[(b*c - a*d)/(b*(c + d*x))]*Log[e*(a + b*x)/(c + d*x)]^2)/(b*d) + ((a + b*x)*Log[e*(a + b*x)/(c + d*x)]^3)/b + (6*(b*c - a*d)*Log[e*(a + b*x)/(c + d*x)]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (6*(b*c - a*d)*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d)}
{Log[e*(a + b*x)/(c + d*x)]^3/(c + d*x)^1, x, 4, -((Log[(b*c - a*d)/(b*(c + d*x))]*Log[(e*(a + b*x))/(c + d*x)]^3)/d) - (3*Log[(e*(a + b*x))/(c + d*x)]^2*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/d + (6*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/d - (6*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/d}
{Log[e*(a + b*x)/(c + d*x)]^3/(c + d*x)^2, x, 4, 6/(d*(c + d*x)) + (6*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/((b*c - a*d)*(c + d*x)) - (3*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/((b*c - a*d)*(c + d*x)) + ((a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^3)/((b*c - a*d)*(c + d*x))}
{Log[e*(a + b*x)/(c + d*x)]^3/(c + d*x)^3, x, 9, (3*d*(a + b*x)^2)/(8*(b*c - a*d)^2*(c + d*x)^2) + (6*b)/(d*(b*c - a*d)*(c + d*x)) - (3*d*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)])/(4*(b*c - a*d)^2*(c + d*x)^2) + (6*b*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)])/((b*c - a*d)^2*(c + d*x)) + (3*d*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)]^2)/(4*(b*c - a*d)^2*(c + d*x)^2) - (3*b*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^2)/((b*c - a*d)^2*(c + d*x)) - (d*(a + b*x)^2*Log[(e*(a + b*x))/(c + d*x)]^3)/(2*(b*c - a*d)^2*(c + d*x)^2) + (b*(a + b*x)*Log[(e*(a + b*x))/(c + d*x)]^3)/((b*c - a*d)^2*(c + d*x))}


{Log[e*(a + b*x)/(c + d*x)]^4, x, 6, (4*(b*c - a*d)*Log[(b*c - a*d)/(b*(c + d*x))]*Log[e*(a + b*x)/(c + d*x)]^3)/(b*d) + ((a + b*x)*Log[e*(a + b*x)/(c + d*x)]^4)/b + (12*(b*c - a*d)*Log[e*(a + b*x)/(c + d*x)]^2*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (24*(b*c - a*d)*Log[e*(a + b*x)/(c + d*x)]*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) + (24*(b*c - a*d)*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d)}


{Log[e*(a + b*x)/(c + d*x)]^5, x, 7, (5*(b*c - a*d)*Log[(b*c - a*d)/(b*(c + d*x))]*Log[e*(a + b*x)/(c + d*x)]^4)/(b*d) + ((a + b*x)*Log[e*(a + b*x)/(c + d*x)]^5)/b + (20*(b*c - a*d)*Log[e*(a + b*x)/(c + d*x)]^3*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (60*(b*c - a*d)*Log[e*(a + b*x)/(c + d*x)]^2*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) + (120*(b*c - a*d)*Log[e*(a + b*x)/(c + d*x)]*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (120*(b*c - a*d)*PolyLog[5, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d)}


{Log[d*(a + b*x)/(b*(c + d*x))]/(c*f + d*f*x), x, 1, PolyLog[2, (b*c - a*d)/(b*(c + d*x))]/(d*f), PolyLog[2, 1 - (d*(a + b*x))/(b*(c + d*x))]/(d*f)}


{Log[1 + 1/(a + b*x)]/(a + b*x), x, 1, PolyLog[2, -(1/(a + b*x))]/b}
{Log[1 - 1/(a + b*x)]/(a + b*x), x, 1, PolyLog[2, 1/(a + b*x)]/b}


(* ::Subsubsection:: *)
(*p<0*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (f+g x)^m Log[e ((a+b x) / (c+d x))^n]^p*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{Log[e*((a + b*x)/(c + d*x))^n]*(f + g*x)^3, x, 3, -(((b*c - a*d)*g*(a^2*d^2*g^2 - a*b*d*g*(4*d*f - c*g) + b^2*(6*d^2*f^2 - 4*c*d*f*g + c^2*g^2))*n*x)/(4*b^3*d^3)) - ((b*c - a*d)*g^2*(4*b*d*f - b*c*g - a*d*g)*n*x^2)/(8*b^2*d^2) - ((b*c - a*d)*g^3*n*x^3)/(12*b*d) - ((b*f - a*g)^4*n*Log[a + b*x])/(4*b^4*g) + ((f + g*x)^4*Log[e*((a + b*x)/(c + d*x))^n])/(4*g) + ((d*f - c*g)^4*n*Log[c + d*x])/(4*d^4*g)}
{Log[e*((a + b*x)/(c + d*x))^n]*(f + g*x)^2, x, 3, -(((b*c - a*d)*g*(3*b*d*f - b*c*g - a*d*g)*n*x)/(3*b^2*d^2)) - ((b*c - a*d)*g^2*n*x^2)/(6*b*d) - ((b*f - a*g)^3*n*Log[a + b*x])/(3*b^3*g) + ((f + g*x)^3*Log[e*((a + b*x)/(c + d*x))^n])/(3*g) + ((d*f - c*g)^3*n*Log[c + d*x])/(3*d^3*g)}
{Log[e*((a + b*x)/(c + d*x))^n]*(f + g*x)^1, x, 3, -(((b*c - a*d)*g*n*x)/(2*b*d)) - ((b*f - a*g)^2*n*Log[a + b*x])/(2*b^2*g) + ((f + g*x)^2*Log[e*((a + b*x)/(c + d*x))^n])/(2*g) + ((d*f - c*g)^2*n*Log[c + d*x])/(2*d^2*g)}
{Log[e*((a + b*x)/(c + d*x))^n]*(f + g*x)^0, x, 3, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/b - ((b*c - a*d)*n*Log[c + d*x])/(b*d)}
{Log[e*((a + b*x)/(c + d*x))^n]/(f + g*x)^1, x, 7, -((n*Log[-((g*(a + b*x))/(b*f - a*g))]*Log[f + g*x])/g) + (Log[e*((a + b*x)/(c + d*x))^n]*Log[f + g*x])/g + (n*Log[-((g*(c + d*x))/(d*f - c*g))]*Log[f + g*x])/g - (n*PolyLog[2, (b*(f + g*x))/(b*f - a*g)])/g + (n*PolyLog[2, (d*(f + g*x))/(d*f - c*g)])/g}
{Log[e*((a + b*x)/(c + d*x))^n]/(f + g*x)^2, x, 4, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/((b*f - a*g)*(f + g*x)) - ((b*c - a*d)*n*Log[c + d*x])/((b*f - a*g)*(d*f - c*g)) + ((b*c - a*d)*n*Log[f + g*x])/((b*f - a*g)*(d*f - c*g))}
{Log[e*((a + b*x)/(c + d*x))^n]/(f + g*x)^3, x, 3, -(((b*c - a*d)*n)/(2*(b*f - a*g)*(d*f - c*g)*(f + g*x))) + (b^2*n*Log[a + b*x])/(2*g*(b*f - a*g)^2) - Log[e*((a + b*x)/(c + d*x))^n]/(2*g*(f + g*x)^2) - (d^2*n*Log[c + d*x])/(2*g*(d*f - c*g)^2) + ((b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n*Log[f + g*x])/(2*(b*f - a*g)^2*(d*f - c*g)^2)}
{Log[e*((a + b*x)/(c + d*x))^n]/(f + g*x)^4, x, 3, -(((b*c - a*d)*n)/(6*(b*f - a*g)*(d*f - c*g)*(f + g*x)^2)) - ((b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n)/(3*(b*f - a*g)^2*(d*f - c*g)^2*(f + g*x)) + (b^3*n*Log[a + b*x])/(3*g*(b*f - a*g)^3) - Log[e*((a + b*x)/(c + d*x))^n]/(3*g*(f + g*x)^3) - (d^3*n*Log[c + d*x])/(3*g*(d*f - c*g)^3) + ((b*c - a*d)*(a^2*d^2*g^2 - a*b*d*g*(3*d*f - c*g) + b^2*(3*d^2*f^2 - 3*c*d*f*g + c^2*g^2))*n*Log[f + g*x])/(3*(b*f - a*g)^3*(d*f - c*g)^3)}


{Log[e*((a + b*x)/(c + d*x))^n]^2*(f + g*x)^3, x, 22, -(((b*c - a*d)^2*(b*c + a*d)*g^3*n^2*x)/(6*b^3*d^3)) + ((b*c - a*d)^2*g^2*(4*b*d*f - b*c*g - a*d*g)*n^2*x)/(4*b^3*d^3) + ((b*c - a*d)^2*g^3*n^2*x^2)/(12*b^2*d^2) - (a^3*(b*c - a*d)*g^3*n^2*Log[a + b*x])/(6*b^4*d) + (a^2*(b*c - a*d)*g^2*(4*b*d*f - b*c*g - a*d*g)*n^2*Log[a + b*x])/(4*b^4*d^2) - ((b*c - a*d)*g^2*(4*b*d*f - b*c*g - a*d*g)*n*x^2*Log[e*((a + b*x)/(c + d*x))^n])/(4*b^2*d^2) - ((b*c - a*d)*g^3*n*x^3*Log[e*((a + b*x)/(c + d*x))^n])/(6*b*d) - ((b*c - a*d)*g*(a^2*d^2*g^2 - a*b*d*g*(4*d*f - c*g) + b^2*(6*d^2*f^2 - 4*c*d*f*g + c^2*g^2))*n*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/(2*b^4*d^3) + ((b*f - a*g)^4*n*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n])/(2*b^4*g) + ((f + g*x)^4*Log[e*((a + b*x)/(c + d*x))^n]^2)/(4*g) - ((d*f - c*g)^4*n*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(2*d^4*g) + (c^3*(b*c - a*d)*g^3*n^2*Log[c + d*x])/(6*b*d^4) - (c^2*(b*c - a*d)*g^2*(4*b*d*f - b*c*g - a*d*g)*n^2*Log[c + d*x])/(4*b^2*d^4) + ((b*c - a*d)^2*g*(a^2*d^2*g^2 - a*b*d*g*(4*d*f - c*g) + b^2*(6*d^2*f^2 - 4*c*d*f*g + c^2*g^2))*n^2*Log[c + d*x])/(2*b^4*d^4) - ((d*f - c*g)^4*n^2*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(2*d^4*g) - ((b*f - a*g)^4*n^2*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(2*b^4*g)}
{Log[e*((a + b*x)/(c + d*x))^n]^2*(f + g*x)^2, x, 19, ((b*c - a*d)^2*g^2*n^2*x)/(3*b^2*d^2) + (a^2*(b*c - a*d)*g^2*n^2*Log[a + b*x])/(3*b^3*d) - ((b*c - a*d)*g^2*n*x^2*Log[e*((a + b*x)/(c + d*x))^n])/(3*b*d) - (2*(b*c - a*d)*g*(3*b*d*f - b*c*g - a*d*g)*n*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/(3*b^3*d^2) + (2*(b*f - a*g)^3*n*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n])/(3*b^3*g) + ((f + g*x)^3*Log[e*((a + b*x)/(c + d*x))^n]^2)/(3*g) - (2*(d*f - c*g)^3*n*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(3*d^3*g) - (c^2*(b*c - a*d)*g^2*n^2*Log[c + d*x])/(3*b*d^3) + (2*(b*c - a*d)^2*g*(3*b*d*f - b*c*g - a*d*g)*n^2*Log[c + d*x])/(3*b^3*d^3) - (2*(d*f - c*g)^3*n^2*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(3*d^3*g) - (2*(b*f - a*g)^3*n^2*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(3*b^3*g)}
{Log[e*((a + b*x)/(c + d*x))^n]^2*(f + g*x)^1, x, 16, -(((b*c - a*d)*g*n*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/(b^2*d)) + ((b*f - a*g)^2*n*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n])/(b^2*g) + ((f + g*x)^2*Log[e*((a + b*x)/(c + d*x))^n]^2)/(2*g) - ((d*f - c*g)^2*n*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(d^2*g) + ((b*c - a*d)^2*g*n^2*Log[c + d*x])/(b^2*d^2) - ((d*f - c*g)^2*n^2*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(d^2*g) - ((b*f - a*g)^2*n^2*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^2*g)}
{Log[e*((a + b*x)/(c + d*x))^n]^2*(f + g*x)^0, x, 7, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^2)/b + (2*(b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(b*d) + (2*(b*c - a*d)*n^2*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b*d)}
{Log[e*((a + b*x)/(c + d*x))^n]^2/(f + g*x)^1, x, 7, -((Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))])/g) + (Log[e*((a + b*x)/(c + d*x))^n]^2*Log[((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/g - (2*n*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/g + (2*n*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/g + (2*n^2*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/g - (2*n^2*PolyLog[3, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/g}
{Log[e*((a + b*x)/(c + d*x))^n]^2/(f + g*x)^2, x, 4, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^2)/((b*f - a*g)*(f + g*x)) + (2*(b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n]*Log[((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/((b*f - a*g)*(d*f - c*g)) + (2*(b*c - a*d)*n^2*PolyLog[2, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/((b*f - a*g)*(d*f - c*g))}
{Log[e*((a + b*x)/(c + d*x))^n]^2/(f + g*x)^3, x, 24, ((b*c - a*d)*g*n*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/((b*f - a*g)^2*(d*f - c*g)*(f + g*x)) - (b^2*n*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n])/(g*(b*f - a*g)^2) - Log[e*((a + b*x)/(c + d*x))^n]^2/(2*g*(f + g*x)^2) + (d^2*n*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(g*(d*f - c*g)^2) - ((b*c - a*d)^2*g*n^2*Log[c + d*x])/((b*f - a*g)^2*(d*f - c*g)^2) + ((b*c - a*d)^2*g*n^2*Log[f + g*x])/((b*f - a*g)^2*(d*f - c*g)^2) - ((b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n^2*Log[-((g*(a + b*x))/(b*f - a*g))]*Log[f + g*x])/((b*f - a*g)^2*(d*f - c*g)^2) + ((b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n*Log[e*((a + b*x)/(c + d*x))^n]*Log[f + g*x])/((b*f - a*g)^2*(d*f - c*g)^2) + ((b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n^2*Log[-((g*(c + d*x))/(d*f - c*g))]*Log[f + g*x])/((b*f - a*g)^2*(d*f - c*g)^2) + (d^2*n^2*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(g*(d*f - c*g)^2) - ((b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n^2*PolyLog[2, (b*(f + g*x))/(b*f - a*g)])/((b*f - a*g)^2*(d*f - c*g)^2) + ((b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n^2*PolyLog[2, (d*(f + g*x))/(d*f - c*g)])/((b*f - a*g)^2*(d*f - c*g)^2) + (b^2*n^2*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(g*(b*f - a*g)^2)}


(* {Log[e*((a + b*x)/(c + d*x))^n]^3*(f + g*x)^3, x, 33, -(((b*c - a*d)^3*g^3*n^3*x)/(4*b^3*d^3)) - (a^2*(b*c - a*d)^2*g^3*n^3*Log[a + b*x])/(4*b^4*d^2) + ((b*c - a*d)^2*g^3*n^2*x^2*Log[e*((a + b*x)/(c + d*x))^n])/(4*b^2*d^2) - ((b*c - a*d)^2*(b*c + a*d)*g^3*n^2*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/(2*b^4*d^3) + (3*(b*c - a*d)^2*g^2*(4*b*d*f - b*c*g - a*d*g)*n^2*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/(4*b^4*d^3) + (a^3*(b*c - a*d)*g^3*n^2*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n])/(2*b^4*d) - (3*a^2*(b*c - a*d)*g^2*(4*b*d*f - b*c*g - a*d*g)*n^2*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n])/(4*b^4*d^2) - (3*(b*c - a*d)*g^2*(4*b*d*f - b*c*g - a*d*g)*n*x^2*Log[e*((a + b*x)/(c + d*x))^n]^2)/(8*b^2*d^2) - ((b*c - a*d)*g^3*n*x^3*Log[e*((a + b*x)/(c + d*x))^n]^2)/(4*b*d) - (3*(b*c - a*d)*g*(a^2*d^2*g^2 - a*b*d*g*(4*d*f - c*g) + b^2*(6*d^2*f^2 - 4*c*d*f*g + c^2*g^2))*n*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^2)/(4*b^4*d^3) + (3*(b*f - a*g)^4*n*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n]^2)/(4*b^4*g) + ((f + g*x)^4*Log[e*((a + b*x)/(c + d*x))^n]^3)/(4*g) - (c^3*(b*c - a*d)*g^3*n^2*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(2*b*d^4) + (3*c^2*(b*c - a*d)*g^2*(4*b*d*f - b*c*g - a*d*g)*n^2*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(4*b^2*d^4) - (3*(b*c - a*d)^2*g*(a^2*d^2*g^2 - a*b*d*g*(4*d*f - c*g) + b^2*(6*d^2*f^2 - 4*c*d*f*g + c^2*g^2))*n^2*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(2*b^4*d^4) - (3*(d*f - c*g)^4*n*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))])/(4*d^4*g) + (c^2*(b*c - a*d)^2*g^3*n^3*Log[c + d*x])/(4*b^2*d^4) + ((b*c - a*d)^3*(b*c + a*d)*g^3*n^3*Log[c + d*x])/(2*b^4*d^4) - (3*(b*c - a*d)^3*g^2*(4*b*d*f - b*c*g - a*d*g)*n^3*Log[c + d*x])/(4*b^4*d^4) - (c^3*(b*c - a*d)*g^3*n^3*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(2*b*d^4) + (3*c^2*(b*c - a*d)*g^2*(4*b*d*f - b*c*g - a*d*g)*n^3*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(4*b^2*d^4) - (3*(b*c - a*d)^2*g*(a^2*d^2*g^2 - a*b*d*g*(4*d*f - c*g) + b^2*(6*d^2*f^2 - 4*c*d*f*g + c^2*g^2))*n^3*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(2*b^4*d^4) - (3*(d*f - c*g)^4*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(2*d^4*g) - (a^3*(b*c - a*d)*g^3*n^3*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(2*b^4*d) + (3*a^2*(b*c - a*d)*g^2*(4*b*d*f - b*c*g - a*d*g)*n^3*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(4*b^4*d^2) - (3*(b*f - a*g)^4*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(2*b^4*g) + (3*(d*f - c*g)^4*n^3*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(2*d^4*g) - (3*(b*f - a*g)^4*n^3*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/(2*b^4*g)} *)
{Log[e*((a + b*x)/(c + d*x))^n]^3*(f + g*x)^2, x, 32, ((b*c - a*d)^2*g^2*n^2*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n])/(b^3*d^2) - (a^2*(b*c - a*d)*g^2*n^2*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n])/(b^3*d) - ((b*c - a*d)*g^2*n*x^2*Log[e*((a + b*x)/(c + d*x))^n]^2)/(2*b*d) - ((b*c - a*d)*g*(3*b*d*f - b*c*g - a*d*g)*n*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^2)/(b^3*d^2) + ((b*f - a*g)^3*n*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n]^2)/(b^3*g) + ((f + g*x)^3*Log[e*((a + b*x)/(c + d*x))^n]^3)/(3*g) + (c^2*(b*c - a*d)*g^2*n^2*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(b*d^3) - (2*(b*c - a*d)^2*g*(3*b*d*f - b*c*g - a*d*g)*n^2*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(b^3*d^3) - ((d*f - c*g)^3*n*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))])/(d^3*g) - ((b*c - a*d)^3*g^2*n^3*Log[c + d*x])/(b^3*d^3) + (c^2*(b*c - a*d)*g^2*n^3*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b*d^3) - (2*(b*c - a*d)^2*g*(3*b*d*f - b*c*g - a*d*g)*n^3*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b^3*d^3) + (a^2*(b*c - a*d)*g^2*n^3*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^3*d) - (2*(b*f - a*g)^3*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^3*g) - (2*(d*f - c*g)^3*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(d^3*g) - (2*(b*f - a*g)^3*n^3*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^3*g) + (2*(d*f - c*g)^3*n^3*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(d^3*g)}
{Log[e*((a + b*x)/(c + d*x))^n]^3*(f + g*x)^1, x, 16, -((3*(b*c - a*d)*g*n*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^2)/(2*b^2*d)) + (3*(b*f - a*g)^2*n*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n]^2)/(2*b^2*g) + ((f + g*x)^2*Log[e*((a + b*x)/(c + d*x))^n]^3)/(2*g) - (3*(b*c - a*d)^2*g*n^2*Log[e*((a + b*x)/(c + d*x))^n]*Log[(b*c - a*d)/(b*(c + d*x))])/(b^2*d^2) - (3*(d*f - c*g)^2*n*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))])/(2*d^2*g) - (3*(b*c - a*d)^2*g*n^3*PolyLog[2, (d*(a + b*x))/(b*(c + d*x))])/(b^2*d^2) - (3*(b*f - a*g)^2*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^2*g) - (3*(d*f - c*g)^2*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(d^2*g) - (3*(b*f - a*g)^2*n^3*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/(b^2*g) + (3*(d*f - c*g)^2*n^3*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(d^2*g)}
{Log[e*((a + b*x)/(c + d*x))^n]^3*(f + g*x)^0, x, 5, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^3)/b + (3*(b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))])/(b*d) + (6*(b*c - a*d)*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (6*(b*c - a*d)*n^3*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d)}
{Log[e*((a + b*x)/(c + d*x))^n]^3/(f + g*x)^1, x, 9, -((Log[e*((a + b*x)/(c + d*x))^n]^3*Log[(b*c - a*d)/(b*(c + d*x))])/g) + (Log[e*((a + b*x)/(c + d*x))^n]^3*Log[((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/g - (3*n*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/g + (3*n*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[2, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/g + (6*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/g - (6*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[3, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/g - (6*n^3*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/g + (6*n^3*PolyLog[4, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/g}
{Log[e*((a + b*x)/(c + d*x))^n]^3/(f + g*x)^2, x, 4, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^3)/((b*f - a*g)*(f + g*x)) + (3*(b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/((b*f - a*g)*(d*f - c*g)) + (6*(b*c - a*d)*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/((b*f - a*g)*(d*f - c*g)) - (6*(b*c - a*d)*n^3*PolyLog[3, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/((b*f - a*g)*(d*f - c*g))}
{Log[e*((a + b*x)/(c + d*x))^n]^3/(f + g*x)^3, x, 20, (3*(b*c - a*d)*g*n*(a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^2)/(2*(b*f - a*g)^2*(d*f - c*g)*(f + g*x)) - (3*b^2*n*Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[e*((a + b*x)/(c + d*x))^n]^2)/(2*g*(b*f - a*g)^2) - Log[e*((a + b*x)/(c + d*x))^n]^3/(2*g*(f + g*x)^2) + (3*d^2*n*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))])/(2*g*(d*f - c*g)^2) - (3*(b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))])/(2*(b*f - a*g)^2*(d*f - c*g)^2) + (3*(b*c - a*d)^2*g*n^2*Log[e*((a + b*x)/(c + d*x))^n]*Log[((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/((b*f - a*g)^2*(d*f - c*g)^2) + (3*(b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(2*(b*f - a*g)^2*(d*f - c*g)^2) + (3*d^2*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(g*(d*f - c*g)^2) - (3*(b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/((b*f - a*g)^2*(d*f - c*g)^2) + (3*(b*c - a*d)^2*g*n^3*PolyLog[2, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/((b*f - a*g)^2*(d*f - c*g)^2) + (3*(b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/((b*f - a*g)^2*(d*f - c*g)^2) + (3*b^2*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(g*(b*f - a*g)^2) - (3*d^2*n^3*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(g*(d*f - c*g)^2) + (3*(b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n^3*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/((b*f - a*g)^2*(d*f - c*g)^2) - (3*(b*c - a*d)*(2*b*d*f - b*c*g - a*d*g)*n^3*PolyLog[3, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/((b*f - a*g)^2*(d*f - c*g)^2) + (3*b^2*n^3*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/(g*(b*f - a*g)^2)}


{Log[e*((a + b*x)/(c + d*x))^n]^4, x, 6, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^4)/b + (4*(b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n]^3*Log[(b*c - a*d)/(b*(c + d*x))])/(b*d) + (12*(b*c - a*d)*n^2*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (24*(b*c - a*d)*n^3*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) + (24*(b*c - a*d)*n^4*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d)}


{Log[e*((a + b*x)/(c + d*x))^n]^5, x, 7, ((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]^5)/b + (5*(b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n]^4*Log[(b*c - a*d)/(b*(c + d*x))])/(b*d) + (20*(b*c - a*d)*n^2*Log[e*((a + b*x)/(c + d*x))^n]^3*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (60*(b*c - a*d)*n^3*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) + (120*(b*c - a*d)*n^4*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d) - (120*(b*c - a*d)*n^5*PolyLog[5, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*d)}


(* ::Subsubsection:: *)
(*p<0*)


(* ::Section::Closed:: *)
(*Integrands of the form Log[i (j (h x)^t)^u]^m Log[e (f (a+b x)^p (c+d x)^q)^r]^s/x*)


{Log[i*(j*(h*x)^t)^u]^3*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/x, x, 13, -((p*r*Log[i*(j*(h*x)^t)^u]^4*Log[1 + (b*x)/a])/(4*t*u)) + (Log[i*(j*(h*x)^t)^u]^4*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(4*t*u) - (q*r*Log[i*(j*(h*x)^t)^u]^4*Log[1 + (d*x)/c])/(4*t*u) - p*r*Log[i*(j*(h*x)^t)^u]^3*PolyLog[2, -((b*x)/a)] - q*r*Log[i*(j*(h*x)^t)^u]^3*PolyLog[2, -((d*x)/c)] + 3*p*r*t*u*Log[i*(j*(h*x)^t)^u]^2*PolyLog[3, -((b*x)/a)] + 3*q*r*t*u*Log[i*(j*(h*x)^t)^u]^2*PolyLog[3, -((d*x)/c)] - 6*p*r*t^2*u^2*Log[i*(j*(h*x)^t)^u]*PolyLog[4, -((b*x)/a)] - 6*q*r*t^2*u^2*Log[i*(j*(h*x)^t)^u]*PolyLog[4, -((d*x)/c)] + 6*p*r*t^3*u^3*PolyLog[5, -((b*x)/a)] + 6*q*r*t^3*u^3*PolyLog[5, -((d*x)/c)]}
{Log[i*(j*(h*x)^t)^u]^2*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/x, x, 11, -((p*r*Log[i*(j*(h*x)^t)^u]^3*Log[1 + (b*x)/a])/(3*t*u)) + (Log[i*(j*(h*x)^t)^u]^3*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(3*t*u) - (q*r*Log[i*(j*(h*x)^t)^u]^3*Log[1 + (d*x)/c])/(3*t*u) - p*r*Log[i*(j*(h*x)^t)^u]^2*PolyLog[2, -((b*x)/a)] - q*r*Log[i*(j*(h*x)^t)^u]^2*PolyLog[2, -((d*x)/c)] + 2*p*r*t*u*Log[i*(j*(h*x)^t)^u]*PolyLog[3, -((b*x)/a)] + 2*q*r*t*u*Log[i*(j*(h*x)^t)^u]*PolyLog[3, -((d*x)/c)] - 2*p*r*t^2*u^2*PolyLog[4, -((b*x)/a)] - 2*q*r*t^2*u^2*PolyLog[4, -((d*x)/c)]}
{Log[i*(j*(h*x)^t)^u]^1*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/x, x, 9, -((p*r*Log[i*(j*(h*x)^t)^u]^2*Log[1 + (b*x)/a])/(2*t*u)) + (Log[i*(j*(h*x)^t)^u]^2*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r])/(2*t*u) - (q*r*Log[i*(j*(h*x)^t)^u]^2*Log[1 + (d*x)/c])/(2*t*u) - p*r*Log[i*(j*(h*x)^t)^u]*PolyLog[2, -((b*x)/a)] - q*r*Log[i*(j*(h*x)^t)^u]*PolyLog[2, -((d*x)/c)] + p*r*t*u*PolyLog[3, -((b*x)/a)] + q*r*t*u*PolyLog[3, -((d*x)/c)]}
{Log[i*(j*(h*x)^t)^u]^0*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/x, x, 5, (-p)*r*Log[x]*Log[1 + (b*x)/a] + Log[x]*Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r] - q*r*Log[x]*Log[1 + (d*x)/c] - p*r*PolyLog[2, -((b*x)/a)] - q*r*PolyLog[2, -((d*x)/c)]}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(x*Log[i*(j*(h*x)^t)^u]^1), x, 0, Unintegrable[Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(x*Log[i*(j*(h*x)^t)^u]), x]}
{Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(x*Log[i*(j*(h*x)^t)^u]^2), x, 0, Unintegrable[Log[e*(f*(a + b*x)^p*(c + d*x)^q)^r]/(x*Log[i*(j*(h*x)^t)^u]^2), x]}


(* Simplification and normalization formerly caused infinite recursion. *)
{Log[x]*Log[(a + b*x)/((b*c - a*d)*x)]^3/x, x, 0, Unintegrable[(Log[x]*Log[(a + b*x)/((b*c - a*d)*x)]^3)/x, x]}
{Log[x]*Log[(a + b*x)/((b*c - a*d)*x)]^2/x, x, 0, Unintegrable[(Log[x]*Log[(a + b*x)/((b*c - a*d)*x)]^2)/x, x]}
{Log[x]*Log[(a + b*x)/((b*c - a*d)*x)]^1/x, x, 5, (-(1/2))*Log[1 + a/(b*x)]*Log[x]^2 + (1/2)*Log[b/(b*c - a*d) + a/((b*c - a*d)*x)]*Log[x]^2 + Log[x]*PolyLog[2, -(a/(b*x))] + PolyLog[3, -(a/(b*x))]}
{Log[x]/(x*Log[(a + b*x)/((b*c - a*d)*x)]^1), x, 0, Unintegrable[Log[x]/(x*Log[(a + b*x)/((b*c - a*d)*x)]), x]}
{Log[x]/(x*Log[(a + b*x)/((b*c - a*d)*x)]^2), x, 0, Unintegrable[Log[x]/(x*Log[(a + b*x)/((b*c - a*d)*x)]^2), x]}


(* ::Section::Closed:: *)
(*Integrands of the form Log[e (f (a+b x)^p (c+d x)^q)^r]^s / ((a+b x) (g+h x))*)


(* ::Subsection::Closed:: *)
(*Integrands of the form Log[e ((a+b x) / (c+d x))^n]^p / ((a+b x) (g+h x))*)


{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^4/((a*h + b*h*x)*(f + g*x)), x, 5, -((Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^4*Log[-(((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x)))])/((b*f - a*g)*h)) + (4*n*n1*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^3*PolyLog[2, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h) + (12*n^2*n1^2*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2*PolyLog[3, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h) + (24*n^3*n1^3*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]*PolyLog[4, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h) + (24*n^4*n1^4*PolyLog[5, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h)}
{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^3/((a*h + b*h*x)*(f + g*x)), x, 4, -((Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^3*Log[-(((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x)))])/((b*f - a*g)*h)) + (3*n*n1*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2*PolyLog[2, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h) + (6*n^2*n1^2*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]*PolyLog[3, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h) + (6*n^3*n1^3*PolyLog[4, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h)}
{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2/((a*h + b*h*x)*(f + g*x)), x, 3, -((Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2*Log[-(((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x)))])/((b*f - a*g)*h)) + (2*n*n1*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]*PolyLog[2, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h) + (2*n^2*n1^2*PolyLog[3, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h)}
{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^1/((a*h + b*h*x)*(f + g*x)), x, 3, -((Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]*Log[-(((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x)))])/((b*f - a*g)*h)) + (n*n1*PolyLog[2, ((b*f - a*g)*(c + d*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h)}
{1/(Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^1*(a*h + b*h*x)*(f + g*x)), x, 0, Unintegrable[1/((f + g*x)*(a*h + b*h*x)*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]), x]}
{1/(Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2*(a*h + b*h*x)*(f + g*x)), x, 0, Unintegrable[1/((f + g*x)*(a*h + b*h*x)*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2), x]}


{Log[(c + d*x)/(a + b*x)]/((a + b*x)*(h*(a - c) + h*(b - d)*x)), x, 2, -(PolyLog[2, 1 - (c + d*x)/(a + b*x)]/((b*c - a*d)*h))}


{Log[(a - c*g + (b - d*g)*x)/(a + b*x)]/((a + b*x)*(c + d*x)), x, 2, PolyLog[2, (g*(c + d*x))/(a + b*x)]/(b*c - a*d)}
{Log[1 - (g*(c + d*x))/(a + b*x)]/((a + b*x)*(c + d*x)), x, 3, PolyLog[2, (g*(c + d*x))/(a + b*x)]/(b*c - a*d)}
{Log[(a - c*g + b*x - d*g*x)/(a + b*x)]/((a + b*x)*(c + d*x)), x, 3, PolyLog[2, (g*(c + d*x))/(a + b*x)]/(b*c - a*d)}


(* ::Subsection::Closed:: *)
(*Integrands of the form Log[e ((a+b x) / (c+d x))^n]^p / (f+g x+h x^2)*)


{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^3/(a*f*h + h*(b*f*x + a*g*x) + b*g*h*x^2), x, 4, -((Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^3*Log[-(((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x)))])/((b*f - a*g)*h)) + (3*n*n1*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2*PolyLog[2, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h) + (6*n^2*n1^2*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]*PolyLog[3, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h) + (6*n^3*n1^3*PolyLog[4, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h)}
{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2/(a*f*h + h*(b*f*x + a*g*x) + b*g*h*x^2), x, 3, -((Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2*Log[-(((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x)))])/((b*f - a*g)*h)) + (2*n*n1*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]*PolyLog[2, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h) + (2*n^2*n1^2*PolyLog[3, 1 + ((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h)}
{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^1/(a*f*h + h*(b*f*x + a*g*x) + b*g*h*x^2), x, 3, -((Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]*Log[-(((b*c - a*d)*(f + g*x))/((d*f - c*g)*(a + b*x)))])/((b*f - a*g)*h)) + (n*n1*PolyLog[2, ((b*f - a*g)*(c + d*x))/((d*f - c*g)*(a + b*x))])/((b*f - a*g)*h)}
{1/Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^1/(a*f*h + h*(b*f*x + a*g*x) + b*g*h*x^2), x, 0, Unintegrable[1/((a*f*h + b*g*h*x^2 + h*(b*f*x + a*g*x))*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]), x]}
{1/Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2/(a*f*h + h*(b*f*x + a*g*x) + b*g*h*x^2), x, 0, Unintegrable[1/((a*f*h + b*g*h*x^2 + h*(b*f*x + a*g*x))*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2), x]}


(* ::Section::Closed:: *)
(*Integrands of the form Log[e (f (a+b x)^p (c+d x)^q)^r]^s / ((a+b x) (c+d x))*)


(* ::Subsection::Closed:: *)
(*Integrands of the form Log[e (f (a+b x)^p / (c+d x)^p)^r]^s / ((a+b x) (c+d x))*)


{Log[e*(f*(a + b*x)/(c + d*x))^r]/((a + b*x)*(c + d*x)), x, 1, Log[e*(f*(a + b*x)/(c + d*x))^r]^2/(2*(b*c - a*d)*r)}


{Log[e*((a + b*x)/(c + d*x))^n]^p/((a + b*x)*(c + d*x)), x, 1, Log[e*((a + b*x)/(c + d*x))^n]^(1 + p)/((b*c - a*d)*n*(1 + p))}
{Log[e*((a + b*x)/(c + d*x))^n]^p/(a*c + (b*c + a*d)*x + b*d*x^2), x, 1, Log[e*((a + b*x)/(c + d*x))^n]^(1 + p)/((b*c - a*d)*n*(1 + p))}


{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^3/((a + b*x)*(c + d*x)), x, 1, Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^4/(4*(b*c - a*d)*n*n1)}
{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2/((a + b*x)*(c + d*x)), x, 1, Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^3/(3*(b*c - a*d)*n*n1)}
{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^1/((a + b*x)*(c + d*x)), x, 1, Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2/(2*(b*c - a*d)*n*n1)}
{1/(Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^1*(a + b*x)*(c + d*x)), x, 1, Log[Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]]/((b*c - a*d)*n*n1)}
{1/(Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2*(a + b*x)*(c + d*x)), x, 1, -(1/((b*c - a*d)*n*n1*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]))}
{1/(Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^3*(a + b*x)*(c + d*x)), x, 1, -(1/(2*(b*c - a*d)*n*n1*Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^2))}


{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^p/((a + b*x)*(c + d*x)), x, 1, Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^(1 + p)/((b*c - a*d)*n*n1*(1 + p))}
{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^p/((a*f + b*f*x)*(c*g + d*g*x)), x, 1, Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^(1 + p)/((b*c - a*d)*f*g*n*n1*(1 + p))}
{Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^p/(a*c*f + (b*c + a*d)*f*x + b*d*f*x^2), x, 1, Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]^(1 + p)/((b*c - a*d)*f*n*n1*(1 + p))}


{1/Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]/((a + b*x)*(c + d*x)), x, 1, Log[Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]]/((b*c - a*d)*n*n1)}
{1/Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]/((a*f + b*f*x)*(c*g + d*g*x)), x, 1, Log[Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]]/((b*c - a*d)*f*g*n*n1)}
{1/Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]/(a*c*f + (b*c + a*d)*f*x + b*d*f*x^2), x, 1, Log[Log[e*((a + b*x)^n1/(c + d*x)^n1)^n]]/((b*c - a*d)*f*n*n1)}


(* ::Section::Closed:: *)
(*Integrands of the form Log[i (j (g+h x)^t)^u]  Log[e (f (a+b x)^p (c+d x)^q)^r]^s / ((a+b x) (c+d x))*)


{Log[h*(f + g*x)^m]/((a + b*x)*(c + d*x))*Log[e*((a + b*x)/(c + d*x))^n]^3, x, 12, (m*Log[e*((a + b*x)/(c + d*x))^n]^4*Log[(b*c - a*d)/(b*(c + d*x))])/(4*(b*c - a*d)*n) - (m*Log[e*((a + b*x)/(c + d*x))^n]^4*Log[((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(4*(b*c - a*d)*n) + (Log[e*((a + b*x)/(c + d*x))^n]^4*Log[h*(f + g*x)^m])/(4*(b*c - a*d)*n) + (m*Log[e*((a + b*x)/(c + d*x))^n]^3*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) - (m*Log[e*((a + b*x)/(c + d*x))^n]^3*PolyLog[2, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(b*c - a*d) - (3*m*n*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) + (3*m*n*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[3, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(b*c - a*d) + (6*m*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) - (6*m*n^2*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[4, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(b*c - a*d) - (6*m*n^3*PolyLog[5, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) + (6*m*n^3*PolyLog[5, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(b*c - a*d)}
{Log[h*(f + g*x)^m]/((a + b*x)*(c + d*x))*Log[e*((a + b*x)/(c + d*x))^n]^2, x, 10, (m*Log[e*((a + b*x)/(c + d*x))^n]^3*Log[(b*c - a*d)/(b*(c + d*x))])/(3*(b*c - a*d)*n) - (m*Log[e*((a + b*x)/(c + d*x))^n]^3*Log[((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(3*(b*c - a*d)*n) + (Log[e*((a + b*x)/(c + d*x))^n]^3*Log[h*(f + g*x)^m])/(3*(b*c - a*d)*n) + (m*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) - (m*Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[2, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(b*c - a*d) - (2*m*n*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) + (2*m*n*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[3, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(b*c - a*d) + (2*m*n^2*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) - (2*m*n^2*PolyLog[4, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(b*c - a*d)}
{Log[h*(f + g*x)^m]/((a + b*x)*(c + d*x))*Log[e*((a + b*x)/(c + d*x))^n]^1, x, 8, (m*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))])/(2*(b*c - a*d)*n) - (m*Log[e*((a + b*x)/(c + d*x))^n]^2*Log[((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(2*(b*c - a*d)*n) + (Log[e*((a + b*x)/(c + d*x))^n]^2*Log[h*(f + g*x)^m])/(2*(b*c - a*d)*n) + (m*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) - (m*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[2, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(b*c - a*d) - (m*n*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) + (m*n*PolyLog[3, 1 - ((b*c - a*d)*(f + g*x))/((b*f - a*g)*(c + d*x))])/(b*c - a*d)}
{Log[h*(f + g*x)^m]/((a + b*x)*(c + d*x))/Log[e*((a + b*x)/(c + d*x))^n]^1, x, 2, (b*CannotIntegrate[Log[h*(f + g*x)^m]/((a + b*x)*Log[e*((a + b*x)/(c + d*x))^n]), x])/(b*c - a*d) - (d*CannotIntegrate[Log[h*(f + g*x)^m]/((c + d*x)*Log[e*((a + b*x)/(c + d*x))^n]), x])/(b*c - a*d)}
{Log[h*(f + g*x)^m]/((a + b*x)*(c + d*x))/Log[e*((a + b*x)/(c + d*x))^n]^2, x, 1, -(Log[h*(f + g*x)^m]/((b*c - a*d)*n*Log[e*((a + b*x)/(c + d*x))^n])) + (g*m*Unintegrable[1/((f + g*x)*Log[e*((a + b*x)/(c + d*x))^n]), x])/((b*c - a*d)*n)}


(* ::Section::Closed:: *)
(*Integrands of the form (f+g x+h x^2)^m Log[1-f (a+b x)/(c+d x)] Log[e ((a+b x) / (c+d x))^n]^p*)


{Log[1 - (a + b*x)/(c + d*x)]/((a + b*x)*(c + d*x)*Log[(a + b*x)/(c + d*x)]^2), x, 2, (b*CannotIntegrate[Log[1 - (a + b*x)/(c + d*x)]/((a + b*x)*Log[(a + b*x)/(c + d*x)]^2), x])/(b*c - a*d) - (d*CannotIntegrate[Log[1 - (a + b*x)/(c + d*x)]/((c + d*x)*Log[(a + b*x)/(c + d*x)]^2), x])/(b*c - a*d)}
{Log[1 - (c + d*x)/(a + b*x)]/((a + b*x)*(c + d*x)*Log[(a + b*x)/(c + d*x)]^2), x, 2, (b*CannotIntegrate[Log[1 - (c + d*x)/(a + b*x)]/((a + b*x)*Log[(a + b*x)/(c + d*x)]^2), x])/(b*c - a*d) - (d*CannotIntegrate[Log[1 - (c + d*x)/(a + b*x)]/((c + d*x)*Log[(a + b*x)/(c + d*x)]^2), x])/(b*c - a*d)}


{Log[1 - (a + b*x)/(c + d*x)]/((a + b*x)*(c + d*x)*Log[(a + b*x)/(c + d*x)]^2) + 1/((c + d*x)*(-a + c + (-b + d)*x)*Log[(a + b*x)/(c + d*x)]), x, -3, -(Log[1 - (a + b*x)/(c + d*x)]/((b*c - a*d)*Log[(a + b*x)/(c + d*x)]))}
{Log[1 - (c + d*x)/(a + b*x)]/((a + b*x)*(c + d*x)*Log[(a + b*x)/(c + d*x)]^2) - 1/((a + b*x)*(a - c + (b - d)*x)*Log[(a + b*x)/(c + d*x)]), x, -3, -(Log[1 - (c + d*x)/(a + b*x)]/((b*c - a*d)*Log[(a + b*x)/(c + d*x)]))}


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n Log[e (f (a+b x)^p (c+d x)^q)^r]^s when m+n+2=0*)


{(a + b*x)^m/((c + d*x)^(m + 2)*Log[e*(f*(a + b*x)^p/(c + d*x)^p)^r]), x, 1, ((a + b*x)^(1 + m)*(c + d*x)^(-1 - m)*ExpIntegralEi[((1 + m)*Log[e*((f*(a + b*x)^p)/(c + d*x)^p)^r])/(p*r)])/((e*((f*(a + b*x)^p)/(c + d*x)^p)^r)^((1 + m)/(p*r))*((b*c - a*d)*p*r))}


{1/((a*h + b*h*x)^2*Log[e*(f*(a + b*x)^p/(c + d*x)^p)^r]), x, 1, ((c + d*x)*(e*((f*(a + b*x)^p)/(c + d*x)^p)^r)^(1/(p*r))*ExpIntegralEi[-(Log[e*((f*(a + b*x)^p)/(c + d*x)^p)^r]/(p*r))])/((b*c - a*d)*h^2*p*r*(a + b*x))}


{(a + b*x)^3/((c + d*x)^5*Log[e*((a + b*x)/(c + d*x))^n]), x, 1, ((a + b*x)^4*ExpIntegralEi[(4*Log[e*((a + b*x)/(c + d*x))^n])/n])/((e*((a + b*x)/(c + d*x))^n)^(4/n)*((b*c - a*d)*n*(c + d*x)^4))}
{(a + b*x)^2/((c + d*x)^4*Log[e*((a + b*x)/(c + d*x))^n]), x, 1, ((a + b*x)^3*ExpIntegralEi[(3*Log[e*((a + b*x)/(c + d*x))^n])/n])/((e*((a + b*x)/(c + d*x))^n)^(3/n)*((b*c - a*d)*n*(c + d*x)^3))}
{(a + b*x)^1/((c + d*x)^3*Log[e*((a + b*x)/(c + d*x))^n]), x, 1, ((a + b*x)^2*ExpIntegralEi[(2*Log[e*((a + b*x)/(c + d*x))^n])/n])/((e*((a + b*x)/(c + d*x))^n)^(2/n)*((b*c - a*d)*n*(c + d*x)^2))}
{(a + b*x)^0/((c + d*x)^2*Log[e*((a + b*x)/(c + d*x))^n]), x, 1, ((a + b*x)*ExpIntegralEi[Log[e*((a + b*x)/(c + d*x))^n]/n])/((e*((a + b*x)/(c + d*x))^n)^n^(-1)*((b*c - a*d)*n*(c + d*x)))}
{1/((a + b*x)^1*(c + d*x)^1*Log[e*((a + b*x)/(c + d*x))^n]), x, 1, Log[Log[e*((a + b*x)/(c + d*x))^n]]/((b*c - a*d)*n)}
{1/((a + b*x)^2*(c + d*x)^0*Log[e*((a + b*x)/(c + d*x))^n]), x, 1, ((e*((a + b*x)/(c + d*x))^n)^(1/n)*(c + d*x)*ExpIntegralEi[-(Log[e*((a + b*x)/(c + d*x))^n]/n)])/((b*c - a*d)*n*(a + b*x))}
{1/((a + b*x)^3*(c + d*x)^(-1)*Log[e*((a + b*x)/(c + d*x))^n]), x, 1, ((e*((a + b*x)/(c + d*x))^n)^(2/n)*(c + d*x)^2*ExpIntegralEi[-((2*Log[e*((a + b*x)/(c + d*x))^n])/n)])/((b*c - a*d)*n*(a + b*x)^2)}
{1/((a + b*x)^4*(c + d*x)^(-2)*Log[e*((a + b*x)/(c + d*x))^n]), x, 1, ((e*((a + b*x)/(c + d*x))^n)^(3/n)*(c + d*x)^3*ExpIntegralEi[-((3*Log[e*((a + b*x)/(c + d*x))^n])/n)])/((b*c - a*d)*n*(a + b*x)^3)}


(* ::Section::Closed:: *)
(*Integrands of the form RFx Log[e (f (a+b x)^p (c+d x)^q)^r]^s*)


{x^3*Log[e*((a + b*x)/(c + d*x))^n]/(f - g*x^2), x, 30, -((a*n*x)/(2*b*g)) + (c*n*x)/(2*d*g) + (a^2*n*Log[a + b*x])/(2*b^2*g) - (n*x^2*Log[a + b*x])/(2*g) - (c^2*n*Log[c + d*x])/(2*d^2*g) + (n*x^2*Log[c + d*x])/(2*g) + (x^2*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/(2*g) - (f*n*Log[a + b*x]*Log[(b*(Sqrt[f] - Sqrt[g]*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*g^2) + (f*n*Log[c + d*x]*Log[(d*(Sqrt[f] - Sqrt[g]*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*g^2) - (f*n*Log[a + b*x]*Log[(b*(Sqrt[f] + Sqrt[g]*x))/(b*Sqrt[f] - a*Sqrt[g])])/(2*g^2) + (f*n*Log[c + d*x]*Log[(d*(Sqrt[f] + Sqrt[g]*x))/(d*Sqrt[f] - c*Sqrt[g])])/(2*g^2) + (f*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])*Log[f - g*x^2])/(2*g^2) - (f*n*PolyLog[2, -((Sqrt[g]*(a + b*x))/(b*Sqrt[f] - a*Sqrt[g]))])/(2*g^2) - (f*n*PolyLog[2, (Sqrt[g]*(a + b*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*g^2) + (f*n*PolyLog[2, -((Sqrt[g]*(c + d*x))/(d*Sqrt[f] - c*Sqrt[g]))])/(2*g^2) + (f*n*PolyLog[2, (Sqrt[g]*(c + d*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*g^2)}
{x^2*Log[e*((a + b*x)/(c + d*x))^n]/(f - g*x^2), x, 27, -((n*(a + b*x)*Log[a + b*x])/(b*g)) + (n*(c + d*x)*Log[c + d*x])/(d*g) + (x*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/g - (Sqrt[f]*ArcTanh[(Sqrt[g]*x)/Sqrt[f]]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/g^(3/2) - (Sqrt[f]*n*Log[a + b*x]*Log[(b*(Sqrt[f] - Sqrt[g]*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*g^(3/2)) + (Sqrt[f]*n*Log[c + d*x]*Log[(d*(Sqrt[f] - Sqrt[g]*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*g^(3/2)) + (Sqrt[f]*n*Log[a + b*x]*Log[(b*(Sqrt[f] + Sqrt[g]*x))/(b*Sqrt[f] - a*Sqrt[g])])/(2*g^(3/2)) - (Sqrt[f]*n*Log[c + d*x]*Log[(d*(Sqrt[f] + Sqrt[g]*x))/(d*Sqrt[f] - c*Sqrt[g])])/(2*g^(3/2)) + (Sqrt[f]*n*PolyLog[2, -((Sqrt[g]*(a + b*x))/(b*Sqrt[f] - a*Sqrt[g]))])/(2*g^(3/2)) - (Sqrt[f]*n*PolyLog[2, (Sqrt[g]*(a + b*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*g^(3/2)) - (Sqrt[f]*n*PolyLog[2, -((Sqrt[g]*(c + d*x))/(d*Sqrt[f] - c*Sqrt[g]))])/(2*g^(3/2)) + (Sqrt[f]*n*PolyLog[2, (Sqrt[g]*(c + d*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*g^(3/2))}
{x^1*Log[e*((a + b*x)/(c + d*x))^n]/(f - g*x^2), x, 18, -((n*Log[a + b*x]*Log[(b*(Sqrt[f] - Sqrt[g]*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*g)) + (n*Log[c + d*x]*Log[(d*(Sqrt[f] - Sqrt[g]*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*g) - (n*Log[a + b*x]*Log[(b*(Sqrt[f] + Sqrt[g]*x))/(b*Sqrt[f] - a*Sqrt[g])])/(2*g) + (n*Log[c + d*x]*Log[(d*(Sqrt[f] + Sqrt[g]*x))/(d*Sqrt[f] - c*Sqrt[g])])/(2*g) + ((n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])*Log[f - g*x^2])/(2*g) - (n*PolyLog[2, -((Sqrt[g]*(a + b*x))/(b*Sqrt[f] - a*Sqrt[g]))])/(2*g) - (n*PolyLog[2, (Sqrt[g]*(a + b*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*g) + (n*PolyLog[2, -((Sqrt[g]*(c + d*x))/(d*Sqrt[f] - c*Sqrt[g]))])/(2*g) + (n*PolyLog[2, (Sqrt[g]*(c + d*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*g)}
{x^0*Log[e*((a + b*x)/(c + d*x))^n]/(f - g*x^2), x, 18, -((ArcTanh[(Sqrt[g]*x)/Sqrt[f]]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/(Sqrt[f]*Sqrt[g])) - (n*Log[a + b*x]*Log[(b*(Sqrt[f] - Sqrt[g]*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*Sqrt[f]*Sqrt[g]) + (n*Log[c + d*x]*Log[(d*(Sqrt[f] - Sqrt[g]*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*Sqrt[f]*Sqrt[g]) + (n*Log[a + b*x]*Log[(b*(Sqrt[f] + Sqrt[g]*x))/(b*Sqrt[f] - a*Sqrt[g])])/(2*Sqrt[f]*Sqrt[g]) - (n*Log[c + d*x]*Log[(d*(Sqrt[f] + Sqrt[g]*x))/(d*Sqrt[f] - c*Sqrt[g])])/(2*Sqrt[f]*Sqrt[g]) + (n*PolyLog[2, -((Sqrt[g]*(a + b*x))/(b*Sqrt[f] - a*Sqrt[g]))])/(2*Sqrt[f]*Sqrt[g]) - (n*PolyLog[2, (Sqrt[g]*(a + b*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*Sqrt[f]*Sqrt[g]) - (n*PolyLog[2, -((Sqrt[g]*(c + d*x))/(d*Sqrt[f] - c*Sqrt[g]))])/(2*Sqrt[f]*Sqrt[g]) + (n*PolyLog[2, (Sqrt[g]*(c + d*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*Sqrt[f]*Sqrt[g])}
{Log[e*((a + b*x)/(c + d*x))^n]/(x^1*(f - g*x^2)), x, 29, (n*Log[-((b*x)/a)]*Log[a + b*x])/f - (n*Log[-((d*x)/c)]*Log[c + d*x])/f - (Log[x]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/f - (n*Log[a + b*x]*Log[(b*(Sqrt[f] - Sqrt[g]*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*f) + (n*Log[c + d*x]*Log[(d*(Sqrt[f] - Sqrt[g]*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*f) - (n*Log[a + b*x]*Log[(b*(Sqrt[f] + Sqrt[g]*x))/(b*Sqrt[f] - a*Sqrt[g])])/(2*f) + (n*Log[c + d*x]*Log[(d*(Sqrt[f] + Sqrt[g]*x))/(d*Sqrt[f] - c*Sqrt[g])])/(2*f) + ((n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])*Log[f - g*x^2])/(2*f) - (n*PolyLog[2, -((Sqrt[g]*(a + b*x))/(b*Sqrt[f] - a*Sqrt[g]))])/(2*f) - (n*PolyLog[2, (Sqrt[g]*(a + b*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*f) + (n*PolyLog[2, 1 + (b*x)/a])/f + (n*PolyLog[2, -((Sqrt[g]*(c + d*x))/(d*Sqrt[f] - c*Sqrt[g]))])/(2*f) + (n*PolyLog[2, (Sqrt[g]*(c + d*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*f) - (n*PolyLog[2, 1 + (d*x)/c])/f}
{Log[e*((a + b*x)/(c + d*x))^n]/(x^2*(f - g*x^2)), x, 31, (b*n*Log[x])/(a*f) - (d*n*Log[x])/(c*f) - (b*n*Log[a + b*x])/(a*f) - (n*Log[a + b*x])/(f*x) + (d*n*Log[c + d*x])/(c*f) + (n*Log[c + d*x])/(f*x) + (n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])/(f*x) - (Sqrt[g]*ArcTanh[(Sqrt[g]*x)/Sqrt[f]]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/f^(3/2) - (Sqrt[g]*n*Log[a + b*x]*Log[(b*(Sqrt[f] - Sqrt[g]*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*f^(3/2)) + (Sqrt[g]*n*Log[c + d*x]*Log[(d*(Sqrt[f] - Sqrt[g]*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*f^(3/2)) + (Sqrt[g]*n*Log[a + b*x]*Log[(b*(Sqrt[f] + Sqrt[g]*x))/(b*Sqrt[f] - a*Sqrt[g])])/(2*f^(3/2)) - (Sqrt[g]*n*Log[c + d*x]*Log[(d*(Sqrt[f] + Sqrt[g]*x))/(d*Sqrt[f] - c*Sqrt[g])])/(2*f^(3/2)) + (Sqrt[g]*n*PolyLog[2, -((Sqrt[g]*(a + b*x))/(b*Sqrt[f] - a*Sqrt[g]))])/(2*f^(3/2)) - (Sqrt[g]*n*PolyLog[2, (Sqrt[g]*(a + b*x))/(b*Sqrt[f] + a*Sqrt[g])])/(2*f^(3/2)) - (Sqrt[g]*n*PolyLog[2, -((Sqrt[g]*(c + d*x))/(d*Sqrt[f] - c*Sqrt[g]))])/(2*f^(3/2)) + (Sqrt[g]*n*PolyLog[2, (Sqrt[g]*(c + d*x))/(d*Sqrt[f] + c*Sqrt[g])])/(2*f^(3/2))}


{x^3*Log[e*((a + b*x)/(c + d*x))^n]/(f + g*x + h*x^2), x, 37, (a*n*x)/(2*b*h) - (c*n*x)/(2*d*h) - (a^2*n*Log[a + b*x])/(2*b^2*h) + (n*x^2*Log[a + b*x])/(2*h) - (g*n*(a + b*x)*Log[a + b*x])/(b*h^2) + (c^2*n*Log[c + d*x])/(2*d^2*h) - (n*x^2*Log[c + d*x])/(2*h) + (g*n*(c + d*x)*Log[c + d*x])/(d*h^2) + (g*x*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/h^2 - (x^2*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/(2*h) - (g*(g^2 - 3*f*h)*ArcTanh[(g + 2*h*x)/Sqrt[g^2 - 4*f*h]]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/(h^3*Sqrt[g^2 - 4*f*h]) + ((g^2 - f*h - (g*(g^2 - 3*f*h))/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h])))])/(2*h^3) - ((g^2 - f*h - (g*(g^2 - 3*f*h))/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h])))])/(2*h^3) + ((g^2 - f*h + (g*(g^2 - 3*f*h))/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h])))])/(2*h^3) - ((g^2 - f*h + (g*(g^2 - 3*f*h))/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h])))])/(2*h^3) - ((g^2 - f*h)*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])*Log[f + g*x + h*x^2])/(2*h^3) + ((g^2 - f*h - (g*(g^2 - 3*f*h))/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h]))])/(2*h^3) + ((g^2 - f*h + (g*(g^2 - 3*f*h))/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h]))])/(2*h^3) - ((g^2 - f*h - (g*(g^2 - 3*f*h))/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h]))])/(2*h^3) - ((g^2 - f*h + (g*(g^2 - 3*f*h))/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h]))])/(2*h^3)}
{x^2*Log[e*((a + b*x)/(c + d*x))^n]/(f + g*x + h*x^2), x, 30, (n*(a + b*x)*Log[a + b*x])/(b*h) - (n*(c + d*x)*Log[c + d*x])/(d*h) - (x*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/h + ((g^2 - 2*f*h)*ArcTanh[(g + 2*h*x)/Sqrt[g^2 - 4*f*h]]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/(h^2*Sqrt[g^2 - 4*f*h]) - ((g - (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h])))])/(2*h^2) + ((g - (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h])))])/(2*h^2) - ((g + (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h])))])/(2*h^2) + ((g + (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h])))])/(2*h^2) + (g*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])*Log[f + g*x + h*x^2])/(2*h^2) - ((g - (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h]))])/(2*h^2) - ((g + (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h]))])/(2*h^2) + ((g - (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h]))])/(2*h^2) + ((g + (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h]))])/(2*h^2)}
{x^1*Log[e*((a + b*x)/(c + d*x))^n]/(f + g*x + h*x^2), x, 21, -((g*ArcTanh[(g + 2*h*x)/Sqrt[g^2 - 4*f*h]]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/(h*Sqrt[g^2 - 4*f*h])) + ((1 - g/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h])))])/(2*h) - ((1 - g/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h])))])/(2*h) + ((1 + g/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h])))])/(2*h) - ((1 + g/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h])))])/(2*h) - ((n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])*Log[f + g*x + h*x^2])/(2*h) + ((1 - g/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h]))])/(2*h) + ((1 + g/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h]))])/(2*h) - ((1 - g/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h]))])/(2*h) - ((1 + g/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h]))])/(2*h)}
{x^0*Log[e*((a + b*x)/(c + d*x))^n]/(f + g*x + h*x^2), x, 19, (2*ArcTanh[(g + 2*h*x)/Sqrt[g^2 - 4*f*h]]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/Sqrt[g^2 - 4*f*h] + (n*Log[a + b*x]*Log[-((b*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h])))])/Sqrt[g^2 - 4*f*h] - (n*Log[c + d*x]*Log[-((d*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h])))])/Sqrt[g^2 - 4*f*h] - (n*Log[a + b*x]*Log[-((b*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h])))])/Sqrt[g^2 - 4*f*h] + (n*Log[c + d*x]*Log[-((d*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h])))])/Sqrt[g^2 - 4*f*h] + (n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h]))])/Sqrt[g^2 - 4*f*h] - (n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h]))])/Sqrt[g^2 - 4*f*h] - (n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h]))])/Sqrt[g^2 - 4*f*h] + (n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h]))])/Sqrt[g^2 - 4*f*h]}
{Log[e*((a + b*x)/(c + d*x))^n]/(x^1*(f + g*x + h*x^2)), x, 31, (n*Log[-((b*x)/a)]*Log[a + b*x])/f - (n*Log[-((d*x)/c)]*Log[c + d*x])/f - (g*ArcTanh[(g + 2*h*x)/Sqrt[g^2 - 4*f*h]]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/(f*Sqrt[g^2 - 4*f*h]) - (Log[x]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/f - ((1 + g/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h])))])/(2*f) + ((1 + g/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h])))])/(2*f) - ((1 - g/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h])))])/(2*f) + ((1 - g/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h])))])/(2*f) + ((n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])*Log[f + g*x + h*x^2])/(2*f) - ((1 + g/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h]))])/(2*f) - ((1 - g/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h]))])/(2*f) + (n*PolyLog[2, 1 + (b*x)/a])/f + ((1 + g/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h]))])/(2*f) + ((1 - g/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h]))])/(2*f) - (n*PolyLog[2, 1 + (d*x)/c])/f}
{Log[e*((a + b*x)/(c + d*x))^n]/(x^2*(f + g*x + h*x^2)), x, 40, (b*n*Log[x])/(a*f) - (d*n*Log[x])/(c*f) - (b*n*Log[a + b*x])/(a*f) - (n*Log[a + b*x])/(f*x) - (g*n*Log[-((b*x)/a)]*Log[a + b*x])/f^2 + (d*n*Log[c + d*x])/(c*f) + (n*Log[c + d*x])/(f*x) + (g*n*Log[-((d*x)/c)]*Log[c + d*x])/f^2 + (n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])/(f*x) + ((g^2 - 2*f*h)*ArcTanh[(g + 2*h*x)/Sqrt[g^2 - 4*f*h]]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/(f^2*Sqrt[g^2 - 4*f*h]) + (g*Log[x]*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x]))/f^2 + ((g + (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h])))])/(2*f^2) - ((g + (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g - Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h])))])/(2*f^2) + ((g - (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*Log[a + b*x]*Log[-((b*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h])))])/(2*f^2) - ((g - (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*Log[c + d*x]*Log[-((d*(g + Sqrt[g^2 - 4*f*h] + 2*h*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h])))])/(2*f^2) - (g*(n*Log[a + b*x] - Log[e*((a + b*x)/(c + d*x))^n] - n*Log[c + d*x])*Log[f + g*x + h*x^2])/(2*f^2) + ((g + (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g - Sqrt[g^2 - 4*f*h]))])/(2*f^2) + ((g - (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(a + b*x))/(2*a*h - b*(g + Sqrt[g^2 - 4*f*h]))])/(2*f^2) - (g*n*PolyLog[2, 1 + (b*x)/a])/f^2 - ((g + (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g - Sqrt[g^2 - 4*f*h]))])/(2*f^2) - ((g - (g^2 - 2*f*h)/Sqrt[g^2 - 4*f*h])*n*PolyLog[2, (2*h*(c + d*x))/(2*c*h - d*(g + Sqrt[g^2 - 4*f*h]))])/(2*f^2) + (g*n*PolyLog[2, 1 + (d*x)/c])/f^2}


(* ::Section::Closed:: *)
(*Miscellaneous integrands involving Log[e (f (a+b x)^p (c+d x)^q)^r]^s*)


{Log[(c*x)/(a + b*x)]/(a + b*x), x, 5, -((Log[a/(a + b*x)]*Log[(c*x)/(a + b*x)])/b) - PolyLog[2, 1 - a/(a + b*x)]/b}
{Log[(c*x)/(a + b*x)]^2/(x*(a + b*x)), x, 1, Log[(c*x)/(a + b*x)]^3/(3*a)}


{(Log[a/(a + b*x)]*Log[(c*x)/(a + b*x)]^2)/(x*(a + b*x)), x, 3, -((Log[(c*x)/(a + b*x)]^2*PolyLog[2, 1 - a/(a + b*x)])/a) + (2*Log[(c*x)/(a + b*x)]*PolyLog[3, 1 - a/(a + b*x)])/a - (2*PolyLog[4, 1 - a/(a + b*x)])/a}


{Log[e*(a + b*x)/(c + d*x)]^2*Log[(b*c - a*d)/(b*(c + d*x))]/((g*a + g*b*x)*(c + d*x)), x, 3, -((Log[(e*(a + b*x))/(c + d*x)]^2*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/((b*c - a*d)*g)) + (2*Log[(e*(a + b*x))/(c + d*x)]*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/((b*c - a*d)*g) - (2*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/((b*c - a*d)*g)}
{Log[e*((a + b*x)/(c + d*x))^n]^2*Log[(b*c - a*d)/(b*(c + d*x))]/((g*a + g*b*x)*(c + d*x)), x, 3, -((Log[e*((a + b*x)/(c + d*x))^n]^2*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/((b*c - a*d)*g)) + (2*n*Log[e*((a + b*x)/(c + d*x))^n]*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/((b*c - a*d)*g) - (2*n^2*PolyLog[4, 1 - (b*c - a*d)/(b*(c + d*x))])/((b*c - a*d)*g)}


{Log[(c*(b + a*x))/x]^1, x, 4, x*Log[a*c + (b*c)/x] + (b*Log[b + a*x])/a}
{Log[(c*(b + a*x))/x]^2, x, 5, ((b + a*x)*Log[a*c + (b*c)/x]^2)/a - (2*b*Log[c*(a + b/x)]*Log[-(b/(a*x))])/a - (2*b*PolyLog[2, 1 + b/(a*x)])/a}
{Log[(c*(b + a*x))/x]^3, x, 7, ((b + a*x)*Log[a*c + (b*c)/x]^3)/a - (3*b*Log[c*(a + b/x)]^2*Log[-(b/(a*x))])/a - (6*b*Log[c*(a + b/x)]*PolyLog[2, 1 + b/(a*x)])/a + (6*b*PolyLog[3, 1 + b/(a*x)])/a}

{Log[(c*(b + a*x)^2)/x^2], x, 3, (2*b*Log[b + a*x])/a + x*Log[(c*(b + a*x)^2)/x^2]}
{Log[(c*(b + a*x)^2)/x^2]^2, x, 7, -((4*b*Log[b/(b + a*x)]*Log[(c*(b + a*x)^2)/x^2])/a) + x*Log[(c*(b + a*x)^2)/x^2]^2 + (8*b*PolyLog[2, 1 - b/(b + a*x)])/a}
{Log[(c*(b + a*x)^2)/x^2]^3, x, 5, -((6*b*Log[b/(b + a*x)]*Log[(c*(b + a*x)^2)/x^2]^2)/a) + x*Log[(c*(b + a*x)^2)/x^2]^3 + (24*b*Log[(c*(b + a*x)^2)/x^2]*PolyLog[2, 1 - b/(b + a*x)])/a + (48*b*PolyLog[3, 1 - b/(b + a*x)])/a}

{Log[(c*x^2)/(b + a*x)^2]^1, x, 3, x*Log[(c*x^2)/(b + a*x)^2] - (2*b*Log[b + a*x])/a}
{Log[(c*x^2)/(b + a*x)^2]^2, x, 7, x*Log[(c*x^2)/(b + a*x)^2]^2 + (4*b*Log[(c*x^2)/(b + a*x)^2]*Log[b/(b + a*x)])/a + (8*b*PolyLog[2, 1 - b/(b + a*x)])/a}
{Log[(c*x^2)/(b + a*x)^2]^3, x, 5, x*Log[(c*x^2)/(b + a*x)^2]^3 + (6*b*Log[(c*x^2)/(b + a*x)^2]^2*Log[b/(b + a*x)])/a + (24*b*Log[(c*x^2)/(b + a*x)^2]*PolyLog[2, 1 - b/(b + a*x)])/a - (48*b*PolyLog[3, 1 - b/(b + a*x)])/a}


{PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))]/((a + b*x)*(c + d*x)), x, 1, -(PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))]/(b*c - a*d))}


{Log[(e*(c + d*x))/(a + b*x)]*Log[((-b)*c + a*d)/(d*(a + b*x))]/((a + b*x)*(c + d*x)), x, 2, (Log[(e*(c + d*x))/(a + b*x)]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/(b*c - a*d) - PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))]/(b*c - a*d)}


{Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2/(a + b*x), x, 3, -((Log[-((b*c - a*d)/(d*(a + b*x)))]*Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2)/b) - (2*Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*PolyLog[2, 1 + (b*c - a*d)/(d*(a + b*x))])/b + (2*PolyLog[3, 1 + (b*c - a*d)/(d*(a + b*x))])/b}


{Log[(e*(c + d*x))/(a + b*x)]*Log[(((-b)*c + a*d)*(e + f*x))/((d*e - c*f)*(a + b*x))]/((a + b*x)*(c + d*x)), x, 2, (Log[(e*(c + d*x))/(a + b*x)]*PolyLog[2, 1 + ((b*c - a*d)*(e + f*x))/((d*e - c*f)*(a + b*x))])/(b*c - a*d) - PolyLog[3, 1 + ((b*c - a*d)*(e + f*x))/((d*e - c*f)*(a + b*x))]/(b*c - a*d)}


{Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2/((a + b*x)*(e + f*x)), x, 3, -((Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2*Log[-(((b*c - a*d)*(e + f*x))/((d*e - c*f)*(a + b*x)))])/(b*e - a*f)) - (2*Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*PolyLog[2, 1 + ((b*c - a*d)*(e + f*x))/((d*e - c*f)*(a + b*x))])/(b*e - a*f) + (2*PolyLog[3, 1 + ((b*c - a*d)*(e + f*x))/((d*e - c*f)*(a + b*x))])/(b*e - a*f)}


{Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2/(e + f*x), x, 7, -((Log[(b*c - a*d)/(b*(c + d*x))]*Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2)/f) + (Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2*Log[((b*c - a*d)*(e + f*x))/((b*e - a*f)*(c + d*x))])/f + (2*Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/f - (2*Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*PolyLog[2, 1 - ((b*c - a*d)*(e + f*x))/((b*e - a*f)*(c + d*x))])/f + (2*PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))])/f - (2*PolyLog[3, 1 - ((b*c - a*d)*(e + f*x))/((b*e - a*f)*(c + d*x))])/f}


{Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*Log[(b*(e + f*x))/(b*e - a*f)]/((a + b*x)*(c + d*x)), x, 8, -((Log[(b*c - a*d)/(b*(c + d*x))]*Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2)/(2*(b*c - a*d))) - (Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2*Log[(b*(e + f*x))/(b*e - a*f)])/(2*(b*c - a*d)) + (Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]^2*Log[((b*c - a*d)*(e + f*x))/((b*e - a*f)*(c + d*x))])/(2*(b*c - a*d)) + (Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*PolyLog[2, 1 - (b*c - a*d)/(b*(c + d*x))])/(b*c - a*d) - (Log[((b*e - a*f)*(c + d*x))/((d*e - c*f)*(a + b*x))]*PolyLog[2, 1 - ((b*c - a*d)*(e + f*x))/((b*e - a*f)*(c + d*x))])/(b*c - a*d) + PolyLog[3, 1 - (b*c - a*d)/(b*(c + d*x))]/(b*c - a*d) - PolyLog[3, 1 - ((b*c - a*d)*(e + f*x))/((b*e - a*f)*(c + d*x))]/(b*c - a*d)}
